/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface V1ThreadsThreadIDClassifyPostRequest {
    threadID: string;
    refresh?: boolean;
}

/**
 * AiApi - interface
 * 
 * @export
 * @interface AiApiInterface
 */
export interface AiApiInterface {
    /**
     * Creates request options for v1AiConfigGet without sending the request
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1AiConfigGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Mode (off/byok/units), model, masked key hint, AI-unit balance, whether the units tier is available on this deployment.
     * @summary Read the tenant\'s AI configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1AiConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Mode (off/byok/units), model, masked key hint, AI-unit balance, whether the units tier is available on this deployment.
     * Read the tenant\'s AI configuration
     */
    v1AiConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1AiConfigPut without sending the request
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1AiConfigPutRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Body: {\"mode\": \"off|byok|units\", \"model\": \"...\", \"anthropic_key\": \"sk-ant-...\"}. BYOK keys are stored AES-256-GCM encrypted; the cleartext is never returned. Omit anthropic_key to keep the stored one.
     * @summary Configure the AI tier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1AiConfigPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Body: {\"mode\": \"off|byok|units\", \"model\": \"...\", \"anthropic_key\": \"sk-ant-...\"}. BYOK keys are stored AES-256-GCM encrypted; the cleartext is never returned. Omit anthropic_key to keep the stored one.
     * Configure the AI tier
     */
    v1AiConfigPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1BillingAiUnitsCheckoutPost without sending the request
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1BillingAiUnitsCheckoutPostRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Body: {\"bundle\": \"100|500|2000\"}. One classification = one unit; bundles expire after 6 months. Admin session required. 503 until Paystack billing is configured.
     * @summary Buy prepaid AI units
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1BillingAiUnitsCheckoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Body: {\"bundle\": \"100|500|2000\"}. One classification = one unit; bundles expire after 6 months. Admin session required. 503 until Paystack billing is configured.
     * Buy prepaid AI units
     */
    v1BillingAiUnitsCheckoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1ThreadsThreadIDClassifyPost without sending the request
     * @param {string} threadID 
     * @param {boolean} [refresh] 
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1ThreadsThreadIDClassifyPostRequestOpts(requestParameters: V1ThreadsThreadIDClassifyPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns {intent, urgency, summary, suggested_action} via the tenant\'s AI tier (BYOK or prepaid units — see /v1/ai-config). Cached per thread state: unchanged threads return the cache free; ?refresh=true forces a re-run. A failed model call charges nothing. 402 when the AI tier is off.
     * @summary LLM-classify a thread
     * @param {string} threadID 
     * @param {boolean} [refresh] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    v1ThreadsThreadIDClassifyPostRaw(requestParameters: V1ThreadsThreadIDClassifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Returns {intent, urgency, summary, suggested_action} via the tenant\'s AI tier (BYOK or prepaid units — see /v1/ai-config). Cached per thread state: unchanged threads return the cache free; ?refresh=true forces a re-run. A failed model call charges nothing. 402 when the AI tier is off.
     * LLM-classify a thread
     */
    v1ThreadsThreadIDClassifyPost(requestParameters: V1ThreadsThreadIDClassifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

}

/**
 * 
 */
export class AiApi extends runtime.BaseAPI implements AiApiInterface {

    /**
     * Creates request options for v1AiConfigGet without sending the request
     */
    async v1AiConfigGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai-config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mode (off/byok/units), model, masked key hint, AI-unit balance, whether the units tier is available on this deployment.
     * Read the tenant\'s AI configuration
     */
    async v1AiConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1AiConfigGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Mode (off/byok/units), model, masked key hint, AI-unit balance, whether the units tier is available on this deployment.
     * Read the tenant\'s AI configuration
     */
    async v1AiConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1AiConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1AiConfigPut without sending the request
     */
    async v1AiConfigPutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai-config`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Body: {\"mode\": \"off|byok|units\", \"model\": \"...\", \"anthropic_key\": \"sk-ant-...\"}. BYOK keys are stored AES-256-GCM encrypted; the cleartext is never returned. Omit anthropic_key to keep the stored one.
     * Configure the AI tier
     */
    async v1AiConfigPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1AiConfigPutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Body: {\"mode\": \"off|byok|units\", \"model\": \"...\", \"anthropic_key\": \"sk-ant-...\"}. BYOK keys are stored AES-256-GCM encrypted; the cleartext is never returned. Omit anthropic_key to keep the stored one.
     * Configure the AI tier
     */
    async v1AiConfigPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1AiConfigPutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1BillingAiUnitsCheckoutPost without sending the request
     */
    async v1BillingAiUnitsCheckoutPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/ai-units/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Body: {\"bundle\": \"100|500|2000\"}. One classification = one unit; bundles expire after 6 months. Admin session required. 503 until Paystack billing is configured.
     * Buy prepaid AI units
     */
    async v1BillingAiUnitsCheckoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1BillingAiUnitsCheckoutPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Body: {\"bundle\": \"100|500|2000\"}. One classification = one unit; bundles expire after 6 months. Admin session required. 503 until Paystack billing is configured.
     * Buy prepaid AI units
     */
    async v1BillingAiUnitsCheckoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1BillingAiUnitsCheckoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1ThreadsThreadIDClassifyPost without sending the request
     */
    async v1ThreadsThreadIDClassifyPostRequestOpts(requestParameters: V1ThreadsThreadIDClassifyPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadID'] == null) {
            throw new runtime.RequiredError(
                'threadID',
                'Required parameter "threadID" was null or undefined when calling v1ThreadsThreadIDClassifyPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['refresh'] != null) {
            queryParameters['refresh'] = requestParameters['refresh'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/threads/{threadID}/classify`;
        urlPath = urlPath.replace('{threadID}', encodeURIComponent(String(requestParameters['threadID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns {intent, urgency, summary, suggested_action} via the tenant\'s AI tier (BYOK or prepaid units — see /v1/ai-config). Cached per thread state: unchanged threads return the cache free; ?refresh=true forces a re-run. A failed model call charges nothing. 402 when the AI tier is off.
     * LLM-classify a thread
     */
    async v1ThreadsThreadIDClassifyPostRaw(requestParameters: V1ThreadsThreadIDClassifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1ThreadsThreadIDClassifyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns {intent, urgency, summary, suggested_action} via the tenant\'s AI tier (BYOK or prepaid units — see /v1/ai-config). Cached per thread state: unchanged threads return the cache free; ?refresh=true forces a re-run. A failed model call charges nothing. 402 when the AI tier is off.
     * LLM-classify a thread
     */
    async v1ThreadsThreadIDClassifyPost(requestParameters: V1ThreadsThreadIDClassifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1ThreadsThreadIDClassifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
