/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Alias,
    AliasFromJSON,
    AliasToJSON,
} from '../models/Alias';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type V1AliasesGet200Response,
    V1AliasesGet200ResponseFromJSON,
    V1AliasesGet200ResponseToJSON,
} from '../models/V1AliasesGet200Response';
import {
    type V1AliasesPostRequest,
    V1AliasesPostRequestFromJSON,
    V1AliasesPostRequestToJSON,
} from '../models/V1AliasesPostRequest';

export interface V1AliasesAddressDeleteRequest {
    address: string;
}

export interface V1AliasesPostOperationRequest {
    v1AliasesPostRequest: V1AliasesPostRequest;
}

/**
 * AliasesApi - interface
 * 
 * @export
 * @interface AliasesApiInterface
 */
export interface AliasesApiInterface {
    /**
     * Creates request options for v1AliasesAddressDelete without sending the request
     * @param {string} address 
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesAddressDeleteRequestOpts(requestParameters: V1AliasesAddressDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Hard-delete (no soft-delete window — aliases are cheap to recreate).
     * @summary Delete an alias
     * @param {string} address 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesAddressDeleteRaw(requestParameters: V1AliasesAddressDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Hard-delete (no soft-delete window — aliases are cheap to recreate).
     * Delete an alias
     */
    v1AliasesAddressDelete(requestParameters: V1AliasesAddressDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for v1AliasesGet without sending the request
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List aliases
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1AliasesGet200Response>>;

    /**
     * List aliases
     */
    v1AliasesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1AliasesGet200Response>;

    /**
     * Creates request options for v1AliasesPost without sending the request
     * @param {V1AliasesPostRequest} v1AliasesPostRequest 
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesPostRequestOpts(requestParameters: V1AliasesPostOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates an email alias. `alias_address` must be on a verified tenant-owned domain. `alias_target` can be any email — intra-tenant or external (forwarding to a Gmail account is a legitimate use). 
     * @summary Create an alias
     * @param {V1AliasesPostRequest} v1AliasesPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AliasesApiInterface
     */
    v1AliasesPostRaw(requestParameters: V1AliasesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Alias>>;

    /**
     * Creates an email alias. `alias_address` must be on a verified tenant-owned domain. `alias_target` can be any email — intra-tenant or external (forwarding to a Gmail account is a legitimate use). 
     * Create an alias
     */
    v1AliasesPost(requestParameters: V1AliasesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Alias>;

}

/**
 * 
 */
export class AliasesApi extends runtime.BaseAPI implements AliasesApiInterface {

    /**
     * Creates request options for v1AliasesAddressDelete without sending the request
     */
    async v1AliasesAddressDeleteRequestOpts(requestParameters: V1AliasesAddressDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling v1AliasesAddressDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/aliases/{address}`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Hard-delete (no soft-delete window — aliases are cheap to recreate).
     * Delete an alias
     */
    async v1AliasesAddressDeleteRaw(requestParameters: V1AliasesAddressDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1AliasesAddressDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Hard-delete (no soft-delete window — aliases are cheap to recreate).
     * Delete an alias
     */
    async v1AliasesAddressDelete(requestParameters: V1AliasesAddressDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1AliasesAddressDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1AliasesGet without sending the request
     */
    async v1AliasesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/aliases`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List aliases
     */
    async v1AliasesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1AliasesGet200Response>> {
        const requestOptions = await this.v1AliasesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1AliasesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List aliases
     */
    async v1AliasesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1AliasesGet200Response> {
        const response = await this.v1AliasesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1AliasesPost without sending the request
     */
    async v1AliasesPostRequestOpts(requestParameters: V1AliasesPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['v1AliasesPostRequest'] == null) {
            throw new runtime.RequiredError(
                'v1AliasesPostRequest',
                'Required parameter "v1AliasesPostRequest" was null or undefined when calling v1AliasesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/aliases`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1AliasesPostRequestToJSON(requestParameters['v1AliasesPostRequest']),
        };
    }

    /**
     * Creates an email alias. `alias_address` must be on a verified tenant-owned domain. `alias_target` can be any email — intra-tenant or external (forwarding to a Gmail account is a legitimate use). 
     * Create an alias
     */
    async v1AliasesPostRaw(requestParameters: V1AliasesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Alias>> {
        const requestOptions = await this.v1AliasesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasFromJSON(jsonValue));
    }

    /**
     * Creates an email alias. `alias_address` must be on a verified tenant-owned domain. `alias_target` can be any email — intra-tenant or external (forwarding to a Gmail account is a legitimate use). 
     * Create an alias
     */
    async v1AliasesPost(requestParameters: V1AliasesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Alias> {
        const response = await this.v1AliasesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
