/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BillingStatus,
    BillingStatusFromJSON,
    BillingStatusToJSON,
} from '../models/BillingStatus';
import {
    type CreateBillingCheckout200Response,
    CreateBillingCheckout200ResponseFromJSON,
    CreateBillingCheckout200ResponseToJSON,
} from '../models/CreateBillingCheckout200Response';
import {
    type CreateBillingCheckoutRequest,
    CreateBillingCheckoutRequestFromJSON,
    CreateBillingCheckoutRequestToJSON,
} from '../models/CreateBillingCheckoutRequest';
import {
    type CreateUnitsCheckout200Response,
    CreateUnitsCheckout200ResponseFromJSON,
    CreateUnitsCheckout200ResponseToJSON,
} from '../models/CreateUnitsCheckout200Response';
import {
    type CreateUnitsCheckoutRequest,
    CreateUnitsCheckoutRequestFromJSON,
    CreateUnitsCheckoutRequestToJSON,
} from '../models/CreateUnitsCheckoutRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface CreateBillingCheckoutOperationRequest {
    createBillingCheckoutRequest: CreateBillingCheckoutRequest;
}

export interface CreateUnitsCheckoutOperationRequest {
    createUnitsCheckoutRequest: CreateUnitsCheckoutRequest;
}

/**
 * BillingApi - interface
 * 
 * @export
 * @interface BillingApiInterface
 */
export interface BillingApiInterface {
    /**
     * Creates request options for createBillingCheckout without sending the request
     * @param {CreateBillingCheckoutRequest} createBillingCheckoutRequest 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingCheckoutRequestOpts(requestParameters: CreateBillingCheckoutOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a plan checkout session
     * @param {CreateBillingCheckoutRequest} createBillingCheckoutRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingCheckoutRaw(requestParameters: CreateBillingCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBillingCheckout200Response>>;

    /**
     * Create a plan checkout session
     */
    createBillingCheckout(requestParameters: CreateBillingCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBillingCheckout200Response>;

    /**
     * Creates request options for createUnitsCheckout without sending the request
     * @param {CreateUnitsCheckoutRequest} createUnitsCheckoutRequest 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createUnitsCheckoutRequestOpts(requestParameters: CreateUnitsCheckoutOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a send-units checkout session
     * @param {CreateUnitsCheckoutRequest} createUnitsCheckoutRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createUnitsCheckoutRaw(requestParameters: CreateUnitsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUnitsCheckout200Response>>;

    /**
     * Create a send-units checkout session
     */
    createUnitsCheckout(requestParameters: CreateUnitsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUnitsCheckout200Response>;

    /**
     * Creates request options for getBilling without sending the request
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getBillingRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get billing status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getBillingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingStatus>>;

    /**
     * Get billing status
     */
    getBilling(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingStatus>;

}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI implements BillingApiInterface {

    /**
     * Creates request options for createBillingCheckout without sending the request
     */
    async createBillingCheckoutRequestOpts(requestParameters: CreateBillingCheckoutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createBillingCheckoutRequest'] == null) {
            throw new runtime.RequiredError(
                'createBillingCheckoutRequest',
                'Required parameter "createBillingCheckoutRequest" was null or undefined when calling createBillingCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBillingCheckoutRequestToJSON(requestParameters['createBillingCheckoutRequest']),
        };
    }

    /**
     * Create a plan checkout session
     */
    async createBillingCheckoutRaw(requestParameters: CreateBillingCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBillingCheckout200Response>> {
        const requestOptions = await this.createBillingCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBillingCheckout200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a plan checkout session
     */
    async createBillingCheckout(requestParameters: CreateBillingCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBillingCheckout200Response> {
        const response = await this.createBillingCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUnitsCheckout without sending the request
     */
    async createUnitsCheckoutRequestOpts(requestParameters: CreateUnitsCheckoutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createUnitsCheckoutRequest'] == null) {
            throw new runtime.RequiredError(
                'createUnitsCheckoutRequest',
                'Required parameter "createUnitsCheckoutRequest" was null or undefined when calling createUnitsCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/units/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUnitsCheckoutRequestToJSON(requestParameters['createUnitsCheckoutRequest']),
        };
    }

    /**
     * Create a send-units checkout session
     */
    async createUnitsCheckoutRaw(requestParameters: CreateUnitsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUnitsCheckout200Response>> {
        const requestOptions = await this.createUnitsCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateUnitsCheckout200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a send-units checkout session
     */
    async createUnitsCheckout(requestParameters: CreateUnitsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUnitsCheckout200Response> {
        const response = await this.createUnitsCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBilling without sending the request
     */
    async getBillingRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get billing status
     */
    async getBillingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingStatus>> {
        const requestOptions = await this.getBillingRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillingStatusFromJSON(jsonValue));
    }

    /**
     * Get billing status
     */
    async getBilling(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingStatus> {
        const response = await this.getBillingRaw(initOverrides);
        return await response.value();
    }

}
