/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetAuditSummary200Response,
    GetAuditSummary200ResponseFromJSON,
    GetAuditSummary200ResponseToJSON,
} from '../models/GetAuditSummary200Response';
import {
    type GetDomainsStatus200Response,
    GetDomainsStatus200ResponseFromJSON,
    GetDomainsStatus200ResponseToJSON,
} from '../models/GetDomainsStatus200Response';
import {
    type GetIntegrationsSummary200Response,
    GetIntegrationsSummary200ResponseFromJSON,
    GetIntegrationsSummary200ResponseToJSON,
} from '../models/GetIntegrationsSummary200Response';
import {
    type GetSecurity200Response,
    GetSecurity200ResponseFromJSON,
    GetSecurity200ResponseToJSON,
} from '../models/GetSecurity200Response';
import {
    type GetStorage200Response,
    GetStorage200ResponseFromJSON,
    GetStorage200ResponseToJSON,
} from '../models/GetStorage200Response';
import {
    type GetUserInsights200Response,
    GetUserInsights200ResponseFromJSON,
    GetUserInsights200ResponseToJSON,
} from '../models/GetUserInsights200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

/**
 * DashboardApi - interface
 * 
 * @export
 * @interface DashboardApiInterface
 */
export interface DashboardApiInterface {
    /**
     * Creates request options for getAuditSummary without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getAuditSummaryRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Audit summary for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getAuditSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAuditSummary200Response>>;

    /**
     * Audit summary for the dashboard
     */
    getAuditSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAuditSummary200Response>;

    /**
     * Creates request options for getDomainsStatus without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getDomainsStatusRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Domain health status for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getDomainsStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDomainsStatus200Response>>;

    /**
     * Domain health status for the dashboard
     */
    getDomainsStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDomainsStatus200Response>;

    /**
     * Creates request options for getIntegrationsSummary without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getIntegrationsSummaryRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Integrations summary for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getIntegrationsSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetIntegrationsSummary200Response>>;

    /**
     * Integrations summary for the dashboard
     */
    getIntegrationsSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetIntegrationsSummary200Response>;

    /**
     * Creates request options for getSecurity without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getSecurityRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Security overview for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getSecurityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSecurity200Response>>;

    /**
     * Security overview for the dashboard
     */
    getSecurity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSecurity200Response>;

    /**
     * Creates request options for getStorage without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getStorageRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Storage usage for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getStorageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStorage200Response>>;

    /**
     * Storage usage for the dashboard
     */
    getStorage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStorage200Response>;

    /**
     * Creates request options for getTenantHealth without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getTenantHealthRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Full tenant health report
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getTenantHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Full tenant health report
     */
    getTenantHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for getUserInsights without sending the request
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getUserInsightsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary User insights for the dashboard
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getUserInsightsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserInsights200Response>>;

    /**
     * User insights for the dashboard
     */
    getUserInsights(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserInsights200Response>;

}

/**
 * 
 */
export class DashboardApi extends runtime.BaseAPI implements DashboardApiInterface {

    /**
     * Creates request options for getAuditSummary without sending the request
     */
    async getAuditSummaryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/audit-summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Audit summary for the dashboard
     */
    async getAuditSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAuditSummary200Response>> {
        const requestOptions = await this.getAuditSummaryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAuditSummary200ResponseFromJSON(jsonValue));
    }

    /**
     * Audit summary for the dashboard
     */
    async getAuditSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAuditSummary200Response> {
        const response = await this.getAuditSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDomainsStatus without sending the request
     */
    async getDomainsStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Domain health status for the dashboard
     */
    async getDomainsStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDomainsStatus200Response>> {
        const requestOptions = await this.getDomainsStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDomainsStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Domain health status for the dashboard
     */
    async getDomainsStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDomainsStatus200Response> {
        const response = await this.getDomainsStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIntegrationsSummary without sending the request
     */
    async getIntegrationsSummaryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/integrations-summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Integrations summary for the dashboard
     */
    async getIntegrationsSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetIntegrationsSummary200Response>> {
        const requestOptions = await this.getIntegrationsSummaryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetIntegrationsSummary200ResponseFromJSON(jsonValue));
    }

    /**
     * Integrations summary for the dashboard
     */
    async getIntegrationsSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetIntegrationsSummary200Response> {
        const response = await this.getIntegrationsSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSecurity without sending the request
     */
    async getSecurityRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/security`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Security overview for the dashboard
     */
    async getSecurityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSecurity200Response>> {
        const requestOptions = await this.getSecurityRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSecurity200ResponseFromJSON(jsonValue));
    }

    /**
     * Security overview for the dashboard
     */
    async getSecurity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSecurity200Response> {
        const response = await this.getSecurityRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStorage without sending the request
     */
    async getStorageRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/storage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Storage usage for the dashboard
     */
    async getStorageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStorage200Response>> {
        const requestOptions = await this.getStorageRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStorage200ResponseFromJSON(jsonValue));
    }

    /**
     * Storage usage for the dashboard
     */
    async getStorage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStorage200Response> {
        const response = await this.getStorageRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTenantHealth without sending the request
     */
    async getTenantHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Full tenant health report
     */
    async getTenantHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getTenantHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Full tenant health report
     */
    async getTenantHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getTenantHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserInsights without sending the request
     */
    async getUserInsightsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/user-insights`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * User insights for the dashboard
     */
    async getUserInsightsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserInsights200Response>> {
        const requestOptions = await this.getUserInsightsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserInsights200ResponseFromJSON(jsonValue));
    }

    /**
     * User insights for the dashboard
     */
    async getUserInsights(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserInsights200Response> {
        const response = await this.getUserInsightsRaw(initOverrides);
        return await response.value();
    }

}
