/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateDistributionListRequest,
    CreateDistributionListRequestFromJSON,
    CreateDistributionListRequestToJSON,
} from '../models/CreateDistributionListRequest';
import {
    type DistributionListDetail,
    DistributionListDetailFromJSON,
    DistributionListDetailToJSON,
} from '../models/DistributionListDetail';
import {
    type ListDistributionLists200Response,
    ListDistributionLists200ResponseFromJSON,
    ListDistributionLists200ResponseToJSON,
} from '../models/ListDistributionLists200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type ReplaceDistributionListMembers200Response,
    ReplaceDistributionListMembers200ResponseFromJSON,
    ReplaceDistributionListMembers200ResponseToJSON,
} from '../models/ReplaceDistributionListMembers200Response';
import {
    type ReplaceDistributionListMembersRequest,
    ReplaceDistributionListMembersRequestFromJSON,
    ReplaceDistributionListMembersRequestToJSON,
} from '../models/ReplaceDistributionListMembersRequest';

export interface CreateDistributionListOperationRequest {
    createDistributionListRequest: CreateDistributionListRequest;
}

export interface DeleteDistributionListRequest {
    address: string;
}

export interface GetDistributionListRequest {
    address: string;
}

export interface ReplaceDistributionListMembersOperationRequest {
    address: string;
    replaceDistributionListMembersRequest: ReplaceDistributionListMembersRequest;
}

/**
 * DistributionListsApi - interface
 * 
 * @export
 * @interface DistributionListsApiInterface
 */
export interface DistributionListsApiInterface {
    /**
     * Creates request options for createDistributionList without sending the request
     * @param {CreateDistributionListRequest} createDistributionListRequest 
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    createDistributionListRequestOpts(requestParameters: CreateDistributionListOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a distribution list
     * @param {CreateDistributionListRequest} createDistributionListRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    createDistributionListRaw(requestParameters: CreateDistributionListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DistributionListDetail>>;

    /**
     * Create a distribution list
     */
    createDistributionList(requestParameters: CreateDistributionListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DistributionListDetail>;

    /**
     * Creates request options for deleteDistributionList without sending the request
     * @param {string} address Distribution list email address
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    deleteDistributionListRequestOpts(requestParameters: DeleteDistributionListRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a distribution list
     * @param {string} address Distribution list email address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    deleteDistributionListRaw(requestParameters: DeleteDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a distribution list
     */
    deleteDistributionList(requestParameters: DeleteDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getDistributionList without sending the request
     * @param {string} address Distribution list email address
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    getDistributionListRequestOpts(requestParameters: GetDistributionListRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a distribution list
     * @param {string} address Distribution list email address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    getDistributionListRaw(requestParameters: GetDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DistributionListDetail>>;

    /**
     * Get a distribution list
     */
    getDistributionList(requestParameters: GetDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DistributionListDetail>;

    /**
     * Creates request options for listDistributionLists without sending the request
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    listDistributionListsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List distribution lists
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    listDistributionListsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDistributionLists200Response>>;

    /**
     * List distribution lists
     */
    listDistributionLists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDistributionLists200Response>;

    /**
     * Creates request options for replaceDistributionListMembers without sending the request
     * @param {string} address Distribution list email address
     * @param {ReplaceDistributionListMembersRequest} replaceDistributionListMembersRequest 
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    replaceDistributionListMembersRequestOpts(requestParameters: ReplaceDistributionListMembersOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Replace distribution list members
     * @param {string} address Distribution list email address
     * @param {ReplaceDistributionListMembersRequest} replaceDistributionListMembersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistributionListsApiInterface
     */
    replaceDistributionListMembersRaw(requestParameters: ReplaceDistributionListMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplaceDistributionListMembers200Response>>;

    /**
     * Replace distribution list members
     */
    replaceDistributionListMembers(requestParameters: ReplaceDistributionListMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplaceDistributionListMembers200Response>;

}

/**
 * 
 */
export class DistributionListsApi extends runtime.BaseAPI implements DistributionListsApiInterface {

    /**
     * Creates request options for createDistributionList without sending the request
     */
    async createDistributionListRequestOpts(requestParameters: CreateDistributionListOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createDistributionListRequest'] == null) {
            throw new runtime.RequiredError(
                'createDistributionListRequest',
                'Required parameter "createDistributionListRequest" was null or undefined when calling createDistributionList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/distribution-lists`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDistributionListRequestToJSON(requestParameters['createDistributionListRequest']),
        };
    }

    /**
     * Create a distribution list
     */
    async createDistributionListRaw(requestParameters: CreateDistributionListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DistributionListDetail>> {
        const requestOptions = await this.createDistributionListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DistributionListDetailFromJSON(jsonValue));
    }

    /**
     * Create a distribution list
     */
    async createDistributionList(requestParameters: CreateDistributionListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DistributionListDetail> {
        const response = await this.createDistributionListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDistributionList without sending the request
     */
    async deleteDistributionListRequestOpts(requestParameters: DeleteDistributionListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling deleteDistributionList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/distribution-lists/{address}`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a distribution list
     */
    async deleteDistributionListRaw(requestParameters: DeleteDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDistributionListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a distribution list
     */
    async deleteDistributionList(requestParameters: DeleteDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDistributionListRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getDistributionList without sending the request
     */
    async getDistributionListRequestOpts(requestParameters: GetDistributionListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getDistributionList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/distribution-lists/{address}`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a distribution list
     */
    async getDistributionListRaw(requestParameters: GetDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DistributionListDetail>> {
        const requestOptions = await this.getDistributionListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DistributionListDetailFromJSON(jsonValue));
    }

    /**
     * Get a distribution list
     */
    async getDistributionList(requestParameters: GetDistributionListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DistributionListDetail> {
        const response = await this.getDistributionListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDistributionLists without sending the request
     */
    async listDistributionListsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/distribution-lists`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List distribution lists
     */
    async listDistributionListsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDistributionLists200Response>> {
        const requestOptions = await this.listDistributionListsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDistributionLists200ResponseFromJSON(jsonValue));
    }

    /**
     * List distribution lists
     */
    async listDistributionLists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDistributionLists200Response> {
        const response = await this.listDistributionListsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for replaceDistributionListMembers without sending the request
     */
    async replaceDistributionListMembersRequestOpts(requestParameters: ReplaceDistributionListMembersOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling replaceDistributionListMembers().'
            );
        }

        if (requestParameters['replaceDistributionListMembersRequest'] == null) {
            throw new runtime.RequiredError(
                'replaceDistributionListMembersRequest',
                'Required parameter "replaceDistributionListMembersRequest" was null or undefined when calling replaceDistributionListMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/distribution-lists/{address}/members`;
        urlPath = urlPath.replace('{address}', encodeURIComponent(String(requestParameters['address'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReplaceDistributionListMembersRequestToJSON(requestParameters['replaceDistributionListMembersRequest']),
        };
    }

    /**
     * Replace distribution list members
     */
    async replaceDistributionListMembersRaw(requestParameters: ReplaceDistributionListMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplaceDistributionListMembers200Response>> {
        const requestOptions = await this.replaceDistributionListMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplaceDistributionListMembers200ResponseFromJSON(jsonValue));
    }

    /**
     * Replace distribution list members
     */
    async replaceDistributionListMembers(requestParameters: ReplaceDistributionListMembersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplaceDistributionListMembers200Response> {
        const response = await this.replaceDistributionListMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
