/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Domain,
    DomainFromJSON,
    DomainToJSON,
} from '../models/Domain';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type V1DomainsGet200Response,
    V1DomainsGet200ResponseFromJSON,
    V1DomainsGet200ResponseToJSON,
} from '../models/V1DomainsGet200Response';
import {
    type V1DomainsPostRequest,
    V1DomainsPostRequestFromJSON,
    V1DomainsPostRequestToJSON,
} from '../models/V1DomainsPostRequest';

export interface V1DomainsDomainDeleteRequest {
    domain: string;
}

export interface V1DomainsDomainGetRequest {
    domain: string;
}

export interface V1DomainsDomainVerifyPostRequest {
    domain: string;
}

export interface V1DomainsPostOperationRequest {
    v1DomainsPostRequest: V1DomainsPostRequest;
}

/**
 * DomainsApi - interface
 * 
 * @export
 * @interface DomainsApiInterface
 */
export interface DomainsApiInterface {
    /**
     * Creates request options for v1DomainsDomainDelete without sending the request
     * @param {string} domain 
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainDeleteRequestOpts(requestParameters: V1DomainsDomainDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Removes the domain registration. Refuses with 409 if any mailbox is still attached — delete the mailboxes first. 
     * @summary Delete a domain
     * @param {string} domain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainDeleteRaw(requestParameters: V1DomainsDomainDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes the domain registration. Refuses with 409 if any mailbox is still attached — delete the mailboxes first. 
     * Delete a domain
     */
    v1DomainsDomainDelete(requestParameters: V1DomainsDomainDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for v1DomainsDomainGet without sending the request
     * @param {string} domain 
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainGetRequestOpts(requestParameters: V1DomainsDomainGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a domain
     * @param {string} domain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainGetRaw(requestParameters: V1DomainsDomainGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>>;

    /**
     * Get a domain
     */
    v1DomainsDomainGet(requestParameters: V1DomainsDomainGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain>;

    /**
     * Creates request options for v1DomainsDomainVerifyPost without sending the request
     * @param {string} domain 
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainVerifyPostRequestOpts(requestParameters: V1DomainsDomainVerifyPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Synchronously checks the `_lockally-verify.<domain>` TXT record against the stored verification token. Returns 200 either way: the returned `verified` boolean tells you whether DNS now confirms. Caller polls until `verified: true`. In v2 a background worker auto-polls and fires a `domain.verified` webhook. 
     * @summary Force-poll DNS verification
     * @param {string} domain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsDomainVerifyPostRaw(requestParameters: V1DomainsDomainVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>>;

    /**
     * Synchronously checks the `_lockally-verify.<domain>` TXT record against the stored verification token. Returns 200 either way: the returned `verified` boolean tells you whether DNS now confirms. Caller polls until `verified: true`. In v2 a background worker auto-polls and fires a `domain.verified` webhook. 
     * Force-poll DNS verification
     */
    v1DomainsDomainVerifyPost(requestParameters: V1DomainsDomainVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain>;

    /**
     * Creates request options for v1DomainsGet without sending the request
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns every domain registered under the calling tenant.
     * @summary List domains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1DomainsGet200Response>>;

    /**
     * Returns every domain registered under the calling tenant.
     * List domains
     */
    v1DomainsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1DomainsGet200Response>;

    /**
     * Creates request options for v1DomainsPost without sending the request
     * @param {V1DomainsPostRequest} v1DomainsPostRequest 
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsPostRequestOpts(requestParameters: V1DomainsPostOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Registers a new domain for the calling tenant. Generates a DKIM keypair and verification token. Returns DNS instructions the tenant must publish under their own DNS (verification TXT, SPF include, DKIM TXT, MX records to `mx1`/`mx2.lockally.com`, DMARC seed).  **Idempotent** — re-posting the same domain returns the existing record with the same DKIM keys and token (regenerating would break the tenant\'s published DNS). Returns 200 on idempotent hit, 201 on first create.  Returns 409 if the domain is already claimed by a different tenant. 
     * @summary Register a domain
     * @param {V1DomainsPostRequest} v1DomainsPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainsApiInterface
     */
    v1DomainsPostRaw(requestParameters: V1DomainsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>>;

    /**
     * Registers a new domain for the calling tenant. Generates a DKIM keypair and verification token. Returns DNS instructions the tenant must publish under their own DNS (verification TXT, SPF include, DKIM TXT, MX records to `mx1`/`mx2.lockally.com`, DMARC seed).  **Idempotent** — re-posting the same domain returns the existing record with the same DKIM keys and token (regenerating would break the tenant\'s published DNS). Returns 200 on idempotent hit, 201 on first create.  Returns 409 if the domain is already claimed by a different tenant. 
     * Register a domain
     */
    v1DomainsPost(requestParameters: V1DomainsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain>;

}

/**
 * 
 */
export class DomainsApi extends runtime.BaseAPI implements DomainsApiInterface {

    /**
     * Creates request options for v1DomainsDomainDelete without sending the request
     */
    async v1DomainsDomainDeleteRequestOpts(requestParameters: V1DomainsDomainDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling v1DomainsDomainDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains/{domain}`;
        urlPath = urlPath.replace('{domain}', encodeURIComponent(String(requestParameters['domain'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes the domain registration. Refuses with 409 if any mailbox is still attached — delete the mailboxes first. 
     * Delete a domain
     */
    async v1DomainsDomainDeleteRaw(requestParameters: V1DomainsDomainDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1DomainsDomainDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the domain registration. Refuses with 409 if any mailbox is still attached — delete the mailboxes first. 
     * Delete a domain
     */
    async v1DomainsDomainDelete(requestParameters: V1DomainsDomainDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1DomainsDomainDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1DomainsDomainGet without sending the request
     */
    async v1DomainsDomainGetRequestOpts(requestParameters: V1DomainsDomainGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling v1DomainsDomainGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains/{domain}`;
        urlPath = urlPath.replace('{domain}', encodeURIComponent(String(requestParameters['domain'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a domain
     */
    async v1DomainsDomainGetRaw(requestParameters: V1DomainsDomainGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>> {
        const requestOptions = await this.v1DomainsDomainGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainFromJSON(jsonValue));
    }

    /**
     * Get a domain
     */
    async v1DomainsDomainGet(requestParameters: V1DomainsDomainGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain> {
        const response = await this.v1DomainsDomainGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DomainsDomainVerifyPost without sending the request
     */
    async v1DomainsDomainVerifyPostRequestOpts(requestParameters: V1DomainsDomainVerifyPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling v1DomainsDomainVerifyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains/{domain}/verify`;
        urlPath = urlPath.replace('{domain}', encodeURIComponent(String(requestParameters['domain'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Synchronously checks the `_lockally-verify.<domain>` TXT record against the stored verification token. Returns 200 either way: the returned `verified` boolean tells you whether DNS now confirms. Caller polls until `verified: true`. In v2 a background worker auto-polls and fires a `domain.verified` webhook. 
     * Force-poll DNS verification
     */
    async v1DomainsDomainVerifyPostRaw(requestParameters: V1DomainsDomainVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>> {
        const requestOptions = await this.v1DomainsDomainVerifyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainFromJSON(jsonValue));
    }

    /**
     * Synchronously checks the `_lockally-verify.<domain>` TXT record against the stored verification token. Returns 200 either way: the returned `verified` boolean tells you whether DNS now confirms. Caller polls until `verified: true`. In v2 a background worker auto-polls and fires a `domain.verified` webhook. 
     * Force-poll DNS verification
     */
    async v1DomainsDomainVerifyPost(requestParameters: V1DomainsDomainVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain> {
        const response = await this.v1DomainsDomainVerifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DomainsGet without sending the request
     */
    async v1DomainsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns every domain registered under the calling tenant.
     * List domains
     */
    async v1DomainsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1DomainsGet200Response>> {
        const requestOptions = await this.v1DomainsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1DomainsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns every domain registered under the calling tenant.
     * List domains
     */
    async v1DomainsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1DomainsGet200Response> {
        const response = await this.v1DomainsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DomainsPost without sending the request
     */
    async v1DomainsPostRequestOpts(requestParameters: V1DomainsPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['v1DomainsPostRequest'] == null) {
            throw new runtime.RequiredError(
                'v1DomainsPostRequest',
                'Required parameter "v1DomainsPostRequest" was null or undefined when calling v1DomainsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/domains`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1DomainsPostRequestToJSON(requestParameters['v1DomainsPostRequest']),
        };
    }

    /**
     * Registers a new domain for the calling tenant. Generates a DKIM keypair and verification token. Returns DNS instructions the tenant must publish under their own DNS (verification TXT, SPF include, DKIM TXT, MX records to `mx1`/`mx2.lockally.com`, DMARC seed).  **Idempotent** — re-posting the same domain returns the existing record with the same DKIM keys and token (regenerating would break the tenant\'s published DNS). Returns 200 on idempotent hit, 201 on first create.  Returns 409 if the domain is already claimed by a different tenant. 
     * Register a domain
     */
    async v1DomainsPostRaw(requestParameters: V1DomainsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Domain>> {
        const requestOptions = await this.v1DomainsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainFromJSON(jsonValue));
    }

    /**
     * Registers a new domain for the calling tenant. Generates a DKIM keypair and verification token. Returns DNS instructions the tenant must publish under their own DNS (verification TXT, SPF include, DKIM TXT, MX records to `mx1`/`mx2.lockally.com`, DMARC seed).  **Idempotent** — re-posting the same domain returns the existing record with the same DKIM keys and token (regenerating would break the tenant\'s published DNS). Returns 200 on idempotent hit, 201 on first create.  Returns 409 if the domain is already claimed by a different tenant. 
     * Register a domain
     */
    async v1DomainsPost(requestParameters: V1DomainsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Domain> {
        const response = await this.v1DomainsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
