/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface V1DraftsDraftIDApprovePostRequest {
    draftID: string;
}

export interface V1DraftsDraftIDCancelPostRequest {
    draftID: string;
}

export interface V1DraftsDraftIDGetRequest {
    draftID: string;
}

export interface V1DraftsDraftIDRejectPostRequest {
    draftID: string;
}

export interface V1DraftsGetRequest {
    status?: string;
    limit?: number;
}

export interface V1InboxesMailboxDraftsPostRequest {
    mailbox: string;
    idempotencyKey: string;
}

export interface V1ThreadsThreadIDDraftsPostRequest {
    threadID: string;
    idempotencyKey: string;
}

/**
 * DraftsApi - interface
 * 
 * @export
 * @interface DraftsApiInterface
 */
export interface DraftsApiInterface {
    /**
     * Creates request options for v1DraftsDraftIDApprovePost without sending the request
     * @param {string} draftID 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDApprovePostRequestOpts(requestParameters: V1DraftsDraftIDApprovePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     * @summary Approve a pending draft (human)
     * @param {string} draftID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDApprovePostRaw(requestParameters: V1DraftsDraftIDApprovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     * Approve a pending draft (human)
     */
    v1DraftsDraftIDApprovePost(requestParameters: V1DraftsDraftIDApprovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1DraftsDraftIDCancelPost without sending the request
     * @param {string} draftID 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDCancelPostRequestOpts(requestParameters: V1DraftsDraftIDCancelPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Only the API key that created the draft may cancel it.
     * @summary Withdraw a pending draft
     * @param {string} draftID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDCancelPostRaw(requestParameters: V1DraftsDraftIDCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Only the API key that created the draft may cancel it.
     * Withdraw a pending draft
     */
    v1DraftsDraftIDCancelPost(requestParameters: V1DraftsDraftIDCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1DraftsDraftIDGet without sending the request
     * @param {string} draftID 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDGetRequestOpts(requestParameters: V1DraftsDraftIDGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a draft
     * @param {string} draftID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDGetRaw(requestParameters: V1DraftsDraftIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Get a draft
     */
    v1DraftsDraftIDGet(requestParameters: V1DraftsDraftIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1DraftsDraftIDRejectPost without sending the request
     * @param {string} draftID 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDRejectPostRequestOpts(requestParameters: V1DraftsDraftIDRejectPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Body: {\"reason\": \"...\"} (optional). Fires draft.rejected.
     * @summary Reject a pending draft (human)
     * @param {string} draftID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsDraftIDRejectPostRaw(requestParameters: V1DraftsDraftIDRejectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Body: {\"reason\": \"...\"} (optional). Fires draft.rejected.
     * Reject a pending draft (human)
     */
    v1DraftsDraftIDRejectPost(requestParameters: V1DraftsDraftIDRejectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1DraftsGet without sending the request
     * @param {string} [status] 
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsGetRequestOpts(requestParameters: V1DraftsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Filter with ?status=pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     * @summary List drafts
     * @param {string} [status] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1DraftsGetRaw(requestParameters: V1DraftsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Filter with ?status=pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     * List drafts
     */
    v1DraftsGet(requestParameters: V1DraftsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1InboxesMailboxDraftsPost without sending the request
     * @param {string} mailbox 
     * @param {string} idempotencyKey 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1InboxesMailboxDraftsPostRequestOpts(requestParameters: V1InboxesMailboxDraftsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     * @summary Propose a new conversation as a draft
     * @param {string} mailbox 
     * @param {string} idempotencyKey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1InboxesMailboxDraftsPostRaw(requestParameters: V1InboxesMailboxDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     * Propose a new conversation as a draft
     */
    v1InboxesMailboxDraftsPost(requestParameters: V1InboxesMailboxDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for v1ThreadsThreadIDDraftsPost without sending the request
     * @param {string} threadID 
     * @param {string} idempotencyKey 
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1ThreadsThreadIDDraftsPostRequestOpts(requestParameters: V1ThreadsThreadIDDraftsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     * @summary Propose a reply as a draft
     * @param {string} threadID 
     * @param {string} idempotencyKey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftsApiInterface
     */
    v1ThreadsThreadIDDraftsPostRaw(requestParameters: V1ThreadsThreadIDDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     * Propose a reply as a draft
     */
    v1ThreadsThreadIDDraftsPost(requestParameters: V1ThreadsThreadIDDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

}

/**
 * 
 */
export class DraftsApi extends runtime.BaseAPI implements DraftsApiInterface {

    /**
     * Creates request options for v1DraftsDraftIDApprovePost without sending the request
     */
    async v1DraftsDraftIDApprovePostRequestOpts(requestParameters: V1DraftsDraftIDApprovePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftID'] == null) {
            throw new runtime.RequiredError(
                'draftID',
                'Required parameter "draftID" was null or undefined when calling v1DraftsDraftIDApprovePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/drafts/{draftID}/approve`;
        urlPath = urlPath.replace('{draftID}', encodeURIComponent(String(requestParameters['draftID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     * Approve a pending draft (human)
     */
    async v1DraftsDraftIDApprovePostRaw(requestParameters: V1DraftsDraftIDApprovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1DraftsDraftIDApprovePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sends the draft exactly as reviewed, through the agent stream (loop detector included). Fires draft.approved.
     * Approve a pending draft (human)
     */
    async v1DraftsDraftIDApprovePost(requestParameters: V1DraftsDraftIDApprovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1DraftsDraftIDApprovePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DraftsDraftIDCancelPost without sending the request
     */
    async v1DraftsDraftIDCancelPostRequestOpts(requestParameters: V1DraftsDraftIDCancelPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftID'] == null) {
            throw new runtime.RequiredError(
                'draftID',
                'Required parameter "draftID" was null or undefined when calling v1DraftsDraftIDCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/drafts/{draftID}/cancel`;
        urlPath = urlPath.replace('{draftID}', encodeURIComponent(String(requestParameters['draftID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Only the API key that created the draft may cancel it.
     * Withdraw a pending draft
     */
    async v1DraftsDraftIDCancelPostRaw(requestParameters: V1DraftsDraftIDCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1DraftsDraftIDCancelPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Only the API key that created the draft may cancel it.
     * Withdraw a pending draft
     */
    async v1DraftsDraftIDCancelPost(requestParameters: V1DraftsDraftIDCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1DraftsDraftIDCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DraftsDraftIDGet without sending the request
     */
    async v1DraftsDraftIDGetRequestOpts(requestParameters: V1DraftsDraftIDGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftID'] == null) {
            throw new runtime.RequiredError(
                'draftID',
                'Required parameter "draftID" was null or undefined when calling v1DraftsDraftIDGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/drafts/{draftID}`;
        urlPath = urlPath.replace('{draftID}', encodeURIComponent(String(requestParameters['draftID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a draft
     */
    async v1DraftsDraftIDGetRaw(requestParameters: V1DraftsDraftIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1DraftsDraftIDGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get a draft
     */
    async v1DraftsDraftIDGet(requestParameters: V1DraftsDraftIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1DraftsDraftIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DraftsDraftIDRejectPost without sending the request
     */
    async v1DraftsDraftIDRejectPostRequestOpts(requestParameters: V1DraftsDraftIDRejectPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftID'] == null) {
            throw new runtime.RequiredError(
                'draftID',
                'Required parameter "draftID" was null or undefined when calling v1DraftsDraftIDRejectPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/drafts/{draftID}/reject`;
        urlPath = urlPath.replace('{draftID}', encodeURIComponent(String(requestParameters['draftID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Body: {\"reason\": \"...\"} (optional). Fires draft.rejected.
     * Reject a pending draft (human)
     */
    async v1DraftsDraftIDRejectPostRaw(requestParameters: V1DraftsDraftIDRejectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1DraftsDraftIDRejectPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Body: {\"reason\": \"...\"} (optional). Fires draft.rejected.
     * Reject a pending draft (human)
     */
    async v1DraftsDraftIDRejectPost(requestParameters: V1DraftsDraftIDRejectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1DraftsDraftIDRejectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1DraftsGet without sending the request
     */
    async v1DraftsGetRequestOpts(requestParameters: V1DraftsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/drafts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Filter with ?status=pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     * List drafts
     */
    async v1DraftsGetRaw(requestParameters: V1DraftsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1DraftsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Filter with ?status=pending_approval|sent|rejected|cancelled. Keys see drafts of granted mailboxes; admin sessions see all.
     * List drafts
     */
    async v1DraftsGet(requestParameters: V1DraftsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1DraftsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1InboxesMailboxDraftsPost without sending the request
     */
    async v1InboxesMailboxDraftsPostRequestOpts(requestParameters: V1InboxesMailboxDraftsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mailbox'] == null) {
            throw new runtime.RequiredError(
                'mailbox',
                'Required parameter "mailbox" was null or undefined when calling v1InboxesMailboxDraftsPost().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling v1InboxesMailboxDraftsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inboxes/{mailbox}/drafts`;
        urlPath = urlPath.replace('{mailbox}', encodeURIComponent(String(requestParameters['mailbox'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     * Propose a new conversation as a draft
     */
    async v1InboxesMailboxDraftsPostRaw(requestParameters: V1InboxesMailboxDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1InboxesMailboxDraftsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * New-conversation drafts ALWAYS require human approval (policy flag new_thread). Idempotency-Key required.
     * Propose a new conversation as a draft
     */
    async v1InboxesMailboxDraftsPost(requestParameters: V1InboxesMailboxDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1InboxesMailboxDraftsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1ThreadsThreadIDDraftsPost without sending the request
     */
    async v1ThreadsThreadIDDraftsPostRequestOpts(requestParameters: V1ThreadsThreadIDDraftsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadID'] == null) {
            throw new runtime.RequiredError(
                'threadID',
                'Required parameter "threadID" was null or undefined when calling v1ThreadsThreadIDDraftsPost().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling v1ThreadsThreadIDDraftsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/threads/{threadID}/drafts`;
        urlPath = urlPath.replace('{threadID}', encodeURIComponent(String(requestParameters['threadID'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     * Propose a reply as a draft
     */
    async v1ThreadsThreadIDDraftsPostRaw(requestParameters: V1ThreadsThreadIDDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.v1ThreadsThreadIDDraftsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The safe default over /reply: the deterministic policy engine auto-sends clean in-thread replies and holds anything risky (PII, new recipients, injection-flagged threads, always-approve mailboxes) for human approval. Fires draft.pending_approval when held. Idempotency-Key required.
     * Propose a reply as a draft
     */
    async v1ThreadsThreadIDDraftsPost(requestParameters: V1ThreadsThreadIDDraftsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.v1ThreadsThreadIDDraftsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
