/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BatchLookupPublicKeys200Response,
    BatchLookupPublicKeys200ResponseFromJSON,
    BatchLookupPublicKeys200ResponseToJSON,
} from '../models/BatchLookupPublicKeys200Response';
import {
    type CreateEncryptionKey201Response,
    CreateEncryptionKey201ResponseFromJSON,
    CreateEncryptionKey201ResponseToJSON,
} from '../models/CreateEncryptionKey201Response';
import {
    type CreateEncryptionKeyRequest,
    CreateEncryptionKeyRequestFromJSON,
    CreateEncryptionKeyRequestToJSON,
} from '../models/CreateEncryptionKeyRequest';
import {
    type CreateEncryptionRecoveryRequest,
    CreateEncryptionRecoveryRequestFromJSON,
    CreateEncryptionRecoveryRequestToJSON,
} from '../models/CreateEncryptionRecoveryRequest';
import {
    type GetEncryptionKey200Response,
    GetEncryptionKey200ResponseFromJSON,
    GetEncryptionKey200ResponseToJSON,
} from '../models/GetEncryptionKey200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RotateEncryptionKeyRequest,
    RotateEncryptionKeyRequestFromJSON,
    RotateEncryptionKeyRequestToJSON,
} from '../models/RotateEncryptionKeyRequest';

export interface BatchLookupPublicKeysRequest {
    emails: string;
}

export interface CreateEncryptionKeyOperationRequest {
    createEncryptionKeyRequest: CreateEncryptionKeyRequest;
}

export interface CreateEncryptionRecoveryOperationRequest {
    createEncryptionRecoveryRequest: CreateEncryptionRecoveryRequest;
}

export interface GetEncryptionKeyRequest {
    email: string;
}

export interface RotateEncryptionKeyOperationRequest {
    rotateEncryptionKeyRequest: RotateEncryptionKeyRequest;
}

/**
 * EncryptionApi - interface
 * 
 * @export
 * @interface EncryptionApiInterface
 */
export interface EncryptionApiInterface {
    /**
     * Creates request options for batchLookupPublicKeys without sending the request
     * @param {string} emails Comma-separated list of email addresses
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    batchLookupPublicKeysRequestOpts(requestParameters: BatchLookupPublicKeysRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Batch-lookup public keys by email
     * @param {string} emails Comma-separated list of email addresses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    batchLookupPublicKeysRaw(requestParameters: BatchLookupPublicKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchLookupPublicKeys200Response>>;

    /**
     * Batch-lookup public keys by email
     */
    batchLookupPublicKeys(requestParameters: BatchLookupPublicKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchLookupPublicKeys200Response>;

    /**
     * Creates request options for createEncryptionKey without sending the request
     * @param {CreateEncryptionKeyRequest} createEncryptionKeyRequest 
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    createEncryptionKeyRequestOpts(requestParameters: CreateEncryptionKeyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Upload an encryption key pair
     * @param {CreateEncryptionKeyRequest} createEncryptionKeyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    createEncryptionKeyRaw(requestParameters: CreateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEncryptionKey201Response>>;

    /**
     * Upload an encryption key pair
     */
    createEncryptionKey(requestParameters: CreateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEncryptionKey201Response>;

    /**
     * Creates request options for createEncryptionRecovery without sending the request
     * @param {CreateEncryptionRecoveryRequest} createEncryptionRecoveryRequest 
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    createEncryptionRecoveryRequestOpts(requestParameters: CreateEncryptionRecoveryOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Store an encryption recovery blob
     * @param {CreateEncryptionRecoveryRequest} createEncryptionRecoveryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    createEncryptionRecoveryRaw(requestParameters: CreateEncryptionRecoveryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Store an encryption recovery blob
     */
    createEncryptionRecovery(requestParameters: CreateEncryptionRecoveryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getEncryptionKey without sending the request
     * @param {string} email 
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    getEncryptionKeyRequestOpts(requestParameters: GetEncryptionKeyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get encryption key for a mailbox
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    getEncryptionKeyRaw(requestParameters: GetEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEncryptionKey200Response>>;

    /**
     * Get encryption key for a mailbox
     */
    getEncryptionKey(requestParameters: GetEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEncryptionKey200Response>;

    /**
     * Creates request options for rotateEncryptionKey without sending the request
     * @param {RotateEncryptionKeyRequest} rotateEncryptionKeyRequest 
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    rotateEncryptionKeyRequestOpts(requestParameters: RotateEncryptionKeyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Rotate an encryption key
     * @param {RotateEncryptionKeyRequest} rotateEncryptionKeyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EncryptionApiInterface
     */
    rotateEncryptionKeyRaw(requestParameters: RotateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Rotate an encryption key
     */
    rotateEncryptionKey(requestParameters: RotateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class EncryptionApi extends runtime.BaseAPI implements EncryptionApiInterface {

    /**
     * Creates request options for batchLookupPublicKeys without sending the request
     */
    async batchLookupPublicKeysRequestOpts(requestParameters: BatchLookupPublicKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emails'] == null) {
            throw new runtime.RequiredError(
                'emails',
                'Required parameter "emails" was null or undefined when calling batchLookupPublicKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['emails'] != null) {
            queryParameters['emails'] = requestParameters['emails'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/encryption/keys/lookup`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Batch-lookup public keys by email
     */
    async batchLookupPublicKeysRaw(requestParameters: BatchLookupPublicKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchLookupPublicKeys200Response>> {
        const requestOptions = await this.batchLookupPublicKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchLookupPublicKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * Batch-lookup public keys by email
     */
    async batchLookupPublicKeys(requestParameters: BatchLookupPublicKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchLookupPublicKeys200Response> {
        const response = await this.batchLookupPublicKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEncryptionKey without sending the request
     */
    async createEncryptionKeyRequestOpts(requestParameters: CreateEncryptionKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEncryptionKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createEncryptionKeyRequest',
                'Required parameter "createEncryptionKeyRequest" was null or undefined when calling createEncryptionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/encryption/keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEncryptionKeyRequestToJSON(requestParameters['createEncryptionKeyRequest']),
        };
    }

    /**
     * Upload an encryption key pair
     */
    async createEncryptionKeyRaw(requestParameters: CreateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEncryptionKey201Response>> {
        const requestOptions = await this.createEncryptionKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEncryptionKey201ResponseFromJSON(jsonValue));
    }

    /**
     * Upload an encryption key pair
     */
    async createEncryptionKey(requestParameters: CreateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEncryptionKey201Response> {
        const response = await this.createEncryptionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEncryptionRecovery without sending the request
     */
    async createEncryptionRecoveryRequestOpts(requestParameters: CreateEncryptionRecoveryOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEncryptionRecoveryRequest'] == null) {
            throw new runtime.RequiredError(
                'createEncryptionRecoveryRequest',
                'Required parameter "createEncryptionRecoveryRequest" was null or undefined when calling createEncryptionRecovery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/encryption/recovery`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEncryptionRecoveryRequestToJSON(requestParameters['createEncryptionRecoveryRequest']),
        };
    }

    /**
     * Store an encryption recovery blob
     */
    async createEncryptionRecoveryRaw(requestParameters: CreateEncryptionRecoveryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createEncryptionRecoveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Store an encryption recovery blob
     */
    async createEncryptionRecovery(requestParameters: CreateEncryptionRecoveryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createEncryptionRecoveryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEncryptionKey without sending the request
     */
    async getEncryptionKeyRequestOpts(requestParameters: GetEncryptionKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling getEncryptionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/encryption/keys/{email}`;
        urlPath = urlPath.replace('{email}', encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get encryption key for a mailbox
     */
    async getEncryptionKeyRaw(requestParameters: GetEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEncryptionKey200Response>> {
        const requestOptions = await this.getEncryptionKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEncryptionKey200ResponseFromJSON(jsonValue));
    }

    /**
     * Get encryption key for a mailbox
     */
    async getEncryptionKey(requestParameters: GetEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEncryptionKey200Response> {
        const response = await this.getEncryptionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateEncryptionKey without sending the request
     */
    async rotateEncryptionKeyRequestOpts(requestParameters: RotateEncryptionKeyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rotateEncryptionKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'rotateEncryptionKeyRequest',
                'Required parameter "rotateEncryptionKeyRequest" was null or undefined when calling rotateEncryptionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/encryption/keys/rotate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RotateEncryptionKeyRequestToJSON(requestParameters['rotateEncryptionKeyRequest']),
        };
    }

    /**
     * Rotate an encryption key
     */
    async rotateEncryptionKeyRaw(requestParameters: RotateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rotateEncryptionKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Rotate an encryption key
     */
    async rotateEncryptionKey(requestParameters: RotateEncryptionKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rotateEncryptionKeyRaw(requestParameters, initOverrides);
    }

}
