/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HealthzGet200Response,
    HealthzGet200ResponseFromJSON,
    HealthzGet200ResponseToJSON,
} from '../models/HealthzGet200Response';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

/**
 * HealthApi - interface
 * 
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
    /**
     * Creates request options for healthzGet without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthzGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns 200 if the process is up and the database pings cleanly. No authentication required.
     * @summary Liveness check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthzGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthzGet200Response>>;

    /**
     * Returns 200 if the process is up and the database pings cleanly. No authentication required.
     * Liveness check
     */
    healthzGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthzGet200Response>;

}

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {

    /**
     * Creates request options for healthzGet without sending the request
     */
    async healthzGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/healthz`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns 200 if the process is up and the database pings cleanly. No authentication required.
     * Liveness check
     */
    async healthzGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthzGet200Response>> {
        const requestOptions = await this.healthzGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthzGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns 200 if the process is up and the database pings cleanly. No authentication required.
     * Liveness check
     */
    async healthzGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthzGet200Response> {
        const response = await this.healthzGetRaw(initOverrides);
        return await response.value();
    }

}
