/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type SignupRequest,
    SignupRequestFromJSON,
    SignupRequestToJSON,
} from '../models/SignupRequest';
import {
    type V1AdminLoginPost200Response,
    V1AdminLoginPost200ResponseFromJSON,
    V1AdminLoginPost200ResponseToJSON,
} from '../models/V1AdminLoginPost200Response';

export interface SignupOperationRequest {
    signupRequest: SignupRequest;
}

/**
 * SignupApi - interface
 * 
 * @export
 * @interface SignupApiInterface
 */
export interface SignupApiInterface {
    /**
     * Creates request options for signup without sending the request
     * @param {SignupRequest} signupRequest 
     * @throws {RequiredError}
     * @memberof SignupApiInterface
     */
    signupRequestOpts(requestParameters: SignupOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Sign up a new tenant
     * @param {SignupRequest} signupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignupApiInterface
     */
    signupRaw(requestParameters: SignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1AdminLoginPost200Response>>;

    /**
     * Sign up a new tenant
     */
    signup(requestParameters: SignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1AdminLoginPost200Response>;

}

/**
 * 
 */
export class SignupApi extends runtime.BaseAPI implements SignupApiInterface {

    /**
     * Creates request options for signup without sending the request
     */
    async signupRequestOpts(requestParameters: SignupOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['signupRequest'] == null) {
            throw new runtime.RequiredError(
                'signupRequest',
                'Required parameter "signupRequest" was null or undefined when calling signup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/signup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestToJSON(requestParameters['signupRequest']),
        };
    }

    /**
     * Sign up a new tenant
     */
    async signupRaw(requestParameters: SignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1AdminLoginPost200Response>> {
        const requestOptions = await this.signupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1AdminLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Sign up a new tenant
     */
    async signup(requestParameters: SignupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1AdminLoginPost200Response> {
        const response = await this.signupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
