/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type Suppression,
    SuppressionFromJSON,
    SuppressionToJSON,
} from '../models/Suppression';
import {
    type V1SuppressionsGet200Response,
    V1SuppressionsGet200ResponseFromJSON,
    V1SuppressionsGet200ResponseToJSON,
} from '../models/V1SuppressionsGet200Response';
import {
    type V1SuppressionsPostRequest,
    V1SuppressionsPostRequestFromJSON,
    V1SuppressionsPostRequestToJSON,
} from '../models/V1SuppressionsPostRequest';

export interface V1SuppressionsEmailDeleteRequest {
    email: string;
}

export interface V1SuppressionsEmailGetRequest {
    email: string;
}

export interface V1SuppressionsGetRequest {
    reason?: V1SuppressionsGetReasonEnum;
    cursor?: string;
    limit?: number;
}

export interface V1SuppressionsPostOperationRequest {
    v1SuppressionsPostRequest: V1SuppressionsPostRequest;
}

/**
 * SuppressionsApi - interface
 * 
 * @export
 * @interface SuppressionsApiInterface
 */
export interface SuppressionsApiInterface {
    /**
     * Creates request options for v1SuppressionsEmailDelete without sending the request
     * @param {string} email 
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsEmailDeleteRequestOpts(requestParameters: V1SuppressionsEmailDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Remove a suppression
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsEmailDeleteRaw(requestParameters: V1SuppressionsEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Remove a suppression
     */
    v1SuppressionsEmailDelete(requestParameters: V1SuppressionsEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for v1SuppressionsEmailGet without sending the request
     * @param {string} email 
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsEmailGetRequestOpts(requestParameters: V1SuppressionsEmailGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Check whether an address is suppressed
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsEmailGetRaw(requestParameters: V1SuppressionsEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>>;

    /**
     * Check whether an address is suppressed
     */
    v1SuppressionsEmailGet(requestParameters: V1SuppressionsEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression>;

    /**
     * Creates request options for v1SuppressionsGet without sending the request
     * @param {'unsubscribe' | 'complaint' | 'bounce' | 'manual'} [reason] 
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsGetRequestOpts(requestParameters: V1SuppressionsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List suppressed recipients
     * @param {'unsubscribe' | 'complaint' | 'bounce' | 'manual'} [reason] 
     * @param {string} [cursor] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsGetRaw(requestParameters: V1SuppressionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SuppressionsGet200Response>>;

    /**
     * List suppressed recipients
     */
    v1SuppressionsGet(requestParameters: V1SuppressionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SuppressionsGet200Response>;

    /**
     * Creates request options for v1SuppressionsPost without sending the request
     * @param {V1SuppressionsPostRequest} v1SuppressionsPostRequest 
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsPostRequestOpts(requestParameters: V1SuppressionsPostOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Add a suppression
     * @param {V1SuppressionsPostRequest} v1SuppressionsPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuppressionsApiInterface
     */
    v1SuppressionsPostRaw(requestParameters: V1SuppressionsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>>;

    /**
     * Add a suppression
     */
    v1SuppressionsPost(requestParameters: V1SuppressionsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression>;

}

/**
 * 
 */
export class SuppressionsApi extends runtime.BaseAPI implements SuppressionsApiInterface {

    /**
     * Creates request options for v1SuppressionsEmailDelete without sending the request
     */
    async v1SuppressionsEmailDeleteRequestOpts(requestParameters: V1SuppressionsEmailDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling v1SuppressionsEmailDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/suppressions/{email}`;
        urlPath = urlPath.replace('{email}', encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a suppression
     */
    async v1SuppressionsEmailDeleteRaw(requestParameters: V1SuppressionsEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1SuppressionsEmailDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a suppression
     */
    async v1SuppressionsEmailDelete(requestParameters: V1SuppressionsEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1SuppressionsEmailDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1SuppressionsEmailGet without sending the request
     */
    async v1SuppressionsEmailGetRequestOpts(requestParameters: V1SuppressionsEmailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling v1SuppressionsEmailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/suppressions/{email}`;
        urlPath = urlPath.replace('{email}', encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check whether an address is suppressed
     */
    async v1SuppressionsEmailGetRaw(requestParameters: V1SuppressionsEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>> {
        const requestOptions = await this.v1SuppressionsEmailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuppressionFromJSON(jsonValue));
    }

    /**
     * Check whether an address is suppressed
     */
    async v1SuppressionsEmailGet(requestParameters: V1SuppressionsEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression> {
        const response = await this.v1SuppressionsEmailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SuppressionsGet without sending the request
     */
    async v1SuppressionsGetRequestOpts(requestParameters: V1SuppressionsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['reason'] != null) {
            queryParameters['reason'] = requestParameters['reason'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/suppressions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List suppressed recipients
     */
    async v1SuppressionsGetRaw(requestParameters: V1SuppressionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SuppressionsGet200Response>> {
        const requestOptions = await this.v1SuppressionsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SuppressionsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List suppressed recipients
     */
    async v1SuppressionsGet(requestParameters: V1SuppressionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SuppressionsGet200Response> {
        const response = await this.v1SuppressionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1SuppressionsPost without sending the request
     */
    async v1SuppressionsPostRequestOpts(requestParameters: V1SuppressionsPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['v1SuppressionsPostRequest'] == null) {
            throw new runtime.RequiredError(
                'v1SuppressionsPostRequest',
                'Required parameter "v1SuppressionsPostRequest" was null or undefined when calling v1SuppressionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/suppressions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1SuppressionsPostRequestToJSON(requestParameters['v1SuppressionsPostRequest']),
        };
    }

    /**
     * Add a suppression
     */
    async v1SuppressionsPostRaw(requestParameters: V1SuppressionsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>> {
        const requestOptions = await this.v1SuppressionsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuppressionFromJSON(jsonValue));
    }

    /**
     * Add a suppression
     */
    async v1SuppressionsPost(requestParameters: V1SuppressionsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression> {
        const response = await this.v1SuppressionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const V1SuppressionsGetReasonEnum = {
    Unsubscribe: 'unsubscribe',
    Complaint: 'complaint',
    Bounce: 'bounce',
    Manual: 'manual'
} as const;
export type V1SuppressionsGetReasonEnum = typeof V1SuppressionsGetReasonEnum[keyof typeof V1SuppressionsGetReasonEnum];
