/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type Tenant,
    TenantFromJSON,
    TenantToJSON,
} from '../models/Tenant';
import {
    type V1UsageGet200Response,
    V1UsageGet200ResponseFromJSON,
    V1UsageGet200ResponseToJSON,
} from '../models/V1UsageGet200Response';

/**
 * TenantApi - interface
 * 
 * @export
 * @interface TenantApiInterface
 */
export interface TenantApiInterface {
    /**
     * Creates request options for v1TenantGet without sending the request
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1TenantGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns the tenant the presented API key belongs to.
     * @summary Get the calling tenant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1TenantGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tenant>>;

    /**
     * Returns the tenant the presented API key belongs to.
     * Get the calling tenant
     */
    v1TenantGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tenant>;

    /**
     * Creates request options for v1UsageGet without sending the request
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1UsageGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns the tenant\'s current usage + cap consumption. Designed for poll-based alerting on the integrator side (e.g. \"warn when daily quota is 80% used\"). Refreshed live from Postgres — there is no cache, so callers should poll at most once per minute. 
     * @summary Usage snapshot
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1UsageGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UsageGet200Response>>;

    /**
     * Returns the tenant\'s current usage + cap consumption. Designed for poll-based alerting on the integrator side (e.g. \"warn when daily quota is 80% used\"). Refreshed live from Postgres — there is no cache, so callers should poll at most once per minute. 
     * Usage snapshot
     */
    v1UsageGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UsageGet200Response>;

}

/**
 * 
 */
export class TenantApi extends runtime.BaseAPI implements TenantApiInterface {

    /**
     * Creates request options for v1TenantGet without sending the request
     */
    async v1TenantGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/tenant`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the tenant the presented API key belongs to.
     * Get the calling tenant
     */
    async v1TenantGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tenant>> {
        const requestOptions = await this.v1TenantGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantFromJSON(jsonValue));
    }

    /**
     * Returns the tenant the presented API key belongs to.
     * Get the calling tenant
     */
    async v1TenantGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tenant> {
        const response = await this.v1TenantGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1UsageGet without sending the request
     */
    async v1UsageGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/usage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the tenant\'s current usage + cap consumption. Designed for poll-based alerting on the integrator side (e.g. \"warn when daily quota is 80% used\"). Refreshed live from Postgres — there is no cache, so callers should poll at most once per minute. 
     * Usage snapshot
     */
    async v1UsageGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UsageGet200Response>> {
        const requestOptions = await this.v1UsageGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1UsageGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the tenant\'s current usage + cap consumption. Designed for poll-based alerting on the integrator side (e.g. \"warn when daily quota is 80% used\"). Refreshed live from Postgres — there is no cache, so callers should poll at most once per minute. 
     * Usage snapshot
     */
    async v1UsageGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UsageGet200Response> {
        const response = await this.v1UsageGetRaw(initOverrides);
        return await response.value();
    }

}
