/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddContactListMemberRequest
 */
export interface AddContactListMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddContactListMemberRequest
     */
    contactId: string;
}

/**
 * Check if a given object implements the AddContactListMemberRequest interface.
 */
export function instanceOfAddContactListMemberRequest(value: object): value is AddContactListMemberRequest {
    if ((!('contactId' in value) && !('contact_id' in value)) || (value['contactId'] === undefined && value['contact_id'] === undefined)) return false;
    return true;
}

export function AddContactListMemberRequestFromJSON(json: any): AddContactListMemberRequest {
    return AddContactListMemberRequestFromJSONTyped(json, false);
}

export function AddContactListMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddContactListMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contact_id'],
    };
}

export function AddContactListMemberRequestToJSON(json: any): AddContactListMemberRequest {
    return AddContactListMemberRequestToJSONTyped(json, false);
}

export function AddContactListMemberRequestToJSONTyped(value?: AddContactListMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact_id': value['contactId'],
    };
}

