/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminFull
 */
export interface AdminFull {
    /**
     * 
     * @type {string}
     * @memberof AdminFull
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminFull
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof AdminFull
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminFull
     */
    displayName?: string;
    /**
     * 
     * @type {AdminFullRoleEnum}
     * @memberof AdminFull
     */
    role: AdminFullRoleEnum;
    /**
     * 
     * @type {Date}
     * @memberof AdminFull
     */
    lastLoginAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminFull
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AdminFull
     */
    disabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminFull
     */
    disabledAt?: Date;
    /**
     * Present ONLY on POST response when lockally generated the password. Shown once.
     * @type {string}
     * @memberof AdminFull
     */
    password?: string;
}


/**
 * @export
 */
export const AdminFullRoleEnum = {
    Admin: 'admin',
    Viewer: 'viewer'
} as const;
export type AdminFullRoleEnum = typeof AdminFullRoleEnum[keyof typeof AdminFullRoleEnum];


/**
 * Check if a given object implements the AdminFull interface.
 */
export function instanceOfAdminFull(value: object): value is AdminFull {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    return true;
}

export function AdminFullFromJSON(json: any): AdminFull {
    return AdminFullFromJSONTyped(json, false);
}

export function AdminFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminFull {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'email': json['email'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'role': json['role'],
        'lastLoginAt': json['last_login_at'] == null ? undefined : (new Date(json['last_login_at'])),
        'createdAt': (new Date(json['created_at'])),
        'disabled': json['disabled'],
        'disabledAt': json['disabled_at'] == null ? undefined : (new Date(json['disabled_at'])),
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AdminFullToJSON(json: any): AdminFull {
    return AdminFullToJSONTyped(json, false);
}

export function AdminFullToJSONTyped(value?: AdminFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'email': value['email'],
        'display_name': value['displayName'],
        'role': value['role'],
        'last_login_at': value['lastLoginAt'] == null ? value['lastLoginAt'] : value['lastLoginAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'disabled': value['disabled'],
        'disabled_at': value['disabledAt'] == null ? value['disabledAt'] : value['disabledAt'].toISOString(),
        'password': value['password'],
    };
}

