/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Alias
 */
export interface Alias {
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    aliasAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    aliasTarget: string;
    /**
     * 
     * @type {Date}
     * @memberof Alias
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Alias interface.
 */
export function instanceOfAlias(value: object): value is Alias {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('aliasAddress' in value) && !('alias_address' in value)) || (value['aliasAddress'] === undefined && value['alias_address'] === undefined)) return false;
    if ((!('aliasTarget' in value) && !('alias_target' in value)) || (value['aliasTarget'] === undefined && value['alias_target'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function AliasFromJSON(json: any): Alias {
    return AliasFromJSONTyped(json, false);
}

export function AliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alias {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'aliasAddress': json['alias_address'],
        'aliasTarget': json['alias_target'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function AliasToJSON(json: any): Alias {
    return AliasToJSONTyped(json, false);
}

export function AliasToJSONTyped(value?: Alias | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'alias_address': value['aliasAddress'],
        'alias_target': value['aliasTarget'],
        'created_at': value['createdAt'].toISOString(),
    };
}

