/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchLookupPublicKeys200ResponseDataInner
 */
export interface BatchLookupPublicKeys200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof BatchLookupPublicKeys200ResponseDataInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchLookupPublicKeys200ResponseDataInner
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchLookupPublicKeys200ResponseDataInner
     */
    keyId?: string;
}

/**
 * Check if a given object implements the BatchLookupPublicKeys200ResponseDataInner interface.
 */
export function instanceOfBatchLookupPublicKeys200ResponseDataInner(value: object): value is BatchLookupPublicKeys200ResponseDataInner {
    return true;
}

export function BatchLookupPublicKeys200ResponseDataInnerFromJSON(json: any): BatchLookupPublicKeys200ResponseDataInner {
    return BatchLookupPublicKeys200ResponseDataInnerFromJSONTyped(json, false);
}

export function BatchLookupPublicKeys200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchLookupPublicKeys200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'keyId': json['key_id'] == null ? undefined : json['key_id'],
    };
}

export function BatchLookupPublicKeys200ResponseDataInnerToJSON(json: any): BatchLookupPublicKeys200ResponseDataInner {
    return BatchLookupPublicKeys200ResponseDataInnerToJSONTyped(json, false);
}

export function BatchLookupPublicKeys200ResponseDataInnerToJSONTyped(value?: BatchLookupPublicKeys200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'public_key': value['publicKey'],
        'key_id': value['keyId'],
    };
}

