/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Calendar
 */
export interface Calendar {
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    description?: string;
    /**
     * 
     * @type {CalendarVisibilityEnum}
     * @memberof Calendar
     */
    visibility: CalendarVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    feedUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Calendar
     */
    eventCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Calendar
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Calendar
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CalendarVisibilityEnum = {
    Private: 'private',
    Tenant: 'tenant'
} as const;
export type CalendarVisibilityEnum = typeof CalendarVisibilityEnum[keyof typeof CalendarVisibilityEnum];


/**
 * Check if a given object implements the Calendar interface.
 */
export function instanceOfCalendar(value: object): value is Calendar {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function CalendarFromJSON(json: any): Calendar {
    return CalendarFromJSONTyped(json, false);
}

export function CalendarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Calendar {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'name': json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'description': json['description'] == null ? undefined : json['description'],
        'visibility': json['visibility'],
        'feedUrl': json['feed_url'] == null ? undefined : json['feed_url'],
        'eventCount': json['event_count'] == null ? undefined : json['event_count'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CalendarToJSON(json: any): Calendar {
    return CalendarToJSONTyped(json, false);
}

export function CalendarToJSONTyped(value?: Calendar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'name': value['name'],
        'color': value['color'],
        'owner_email': value['ownerEmail'],
        'description': value['description'],
        'visibility': value['visibility'],
        'feed_url': value['feedUrl'],
        'event_count': value['eventCount'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

