/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBillingCheckout200Response
 */
export interface CreateBillingCheckout200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateBillingCheckout200Response
     */
    authorizationUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBillingCheckout200Response
     */
    reference: string;
}

/**
 * Check if a given object implements the CreateBillingCheckout200Response interface.
 */
export function instanceOfCreateBillingCheckout200Response(value: object): value is CreateBillingCheckout200Response {
    if ((!('authorizationUrl' in value) && !('authorization_url' in value)) || (value['authorizationUrl'] === undefined && value['authorization_url'] === undefined)) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function CreateBillingCheckout200ResponseFromJSON(json: any): CreateBillingCheckout200Response {
    return CreateBillingCheckout200ResponseFromJSONTyped(json, false);
}

export function CreateBillingCheckout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBillingCheckout200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationUrl': json['authorization_url'],
        'reference': json['reference'],
    };
}

export function CreateBillingCheckout200ResponseToJSON(json: any): CreateBillingCheckout200Response {
    return CreateBillingCheckout200ResponseToJSONTyped(json, false);
}

export function CreateBillingCheckout200ResponseToJSONTyped(value?: CreateBillingCheckout200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization_url': value['authorizationUrl'],
        'reference': value['reference'],
    };
}

