/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDistributionListRequest
 */
export interface CreateDistributionListRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDistributionListRequest
     */
    listAddress: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDistributionListRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDistributionListRequest
     */
    members?: Array<string>;
}

/**
 * Check if a given object implements the CreateDistributionListRequest interface.
 */
export function instanceOfCreateDistributionListRequest(value: object): value is CreateDistributionListRequest {
    if ((!('listAddress' in value) && !('list_address' in value)) || (value['listAddress'] === undefined && value['list_address'] === undefined)) return false;
    return true;
}

export function CreateDistributionListRequestFromJSON(json: any): CreateDistributionListRequest {
    return CreateDistributionListRequestFromJSONTyped(json, false);
}

export function CreateDistributionListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDistributionListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listAddress': json['list_address'],
        'name': json['name'] == null ? undefined : json['name'],
        'members': json['members'] == null ? undefined : json['members'],
    };
}

export function CreateDistributionListRequestToJSON(json: any): CreateDistributionListRequest {
    return CreateDistributionListRequestToJSONTyped(json, false);
}

export function CreateDistributionListRequestToJSONTyped(value?: CreateDistributionListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list_address': value['listAddress'],
        'name': value['name'],
        'members': value['members'],
    };
}

