/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEncryptionKeyRequest
 */
export interface CreateEncryptionKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEncryptionKeyRequest
     */
    mailboxEmail: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEncryptionKeyRequest
     */
    publicKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEncryptionKeyRequest
     */
    encryptedPrivateKey: string;
    /**
     * 
     * @type {object}
     * @memberof CreateEncryptionKeyRequest
     */
    kdfParams?: object;
}

/**
 * Check if a given object implements the CreateEncryptionKeyRequest interface.
 */
export function instanceOfCreateEncryptionKeyRequest(value: object): value is CreateEncryptionKeyRequest {
    if ((!('mailboxEmail' in value) && !('mailbox_email' in value)) || (value['mailboxEmail'] === undefined && value['mailbox_email'] === undefined)) return false;
    if ((!('publicKey' in value) && !('public_key' in value)) || (value['publicKey'] === undefined && value['public_key'] === undefined)) return false;
    if ((!('encryptedPrivateKey' in value) && !('encrypted_private_key' in value)) || (value['encryptedPrivateKey'] === undefined && value['encrypted_private_key'] === undefined)) return false;
    return true;
}

export function CreateEncryptionKeyRequestFromJSON(json: any): CreateEncryptionKeyRequest {
    return CreateEncryptionKeyRequestFromJSONTyped(json, false);
}

export function CreateEncryptionKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEncryptionKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mailboxEmail': json['mailbox_email'],
        'publicKey': json['public_key'],
        'encryptedPrivateKey': json['encrypted_private_key'],
        'kdfParams': json['kdf_params'] == null ? undefined : json['kdf_params'],
    };
}

export function CreateEncryptionKeyRequestToJSON(json: any): CreateEncryptionKeyRequest {
    return CreateEncryptionKeyRequestToJSONTyped(json, false);
}

export function CreateEncryptionKeyRequestToJSONTyped(value?: CreateEncryptionKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailbox_email': value['mailboxEmail'],
        'public_key': value['publicKey'],
        'encrypted_private_key': value['encryptedPrivateKey'],
        'kdf_params': value['kdfParams'],
    };
}

