/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateContactRequest
 */
export interface CreateContactRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    notes?: string;
    /**
     * 
     * @type {CreateContactRequestContactTypeEnum}
     * @memberof CreateContactRequest
     */
    contactType?: CreateContactRequestContactTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContactRequest
     */
    role?: string;
}


/**
 * @export
 */
export const CreateContactRequestContactTypeEnum = {
    Internal: 'internal',
    External: 'external'
} as const;
export type CreateContactRequestContactTypeEnum = typeof CreateContactRequestContactTypeEnum[keyof typeof CreateContactRequestContactTypeEnum];


/**
 * Check if a given object implements the CreateContactRequest interface.
 */
export function instanceOfCreateContactRequest(value: object): value is CreateContactRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateContactRequestFromJSON(json: any): CreateContactRequest {
    return CreateContactRequestFromJSONTyped(json, false);
}

export function CreateContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'company': json['company'] == null ? undefined : json['company'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'contactType': json['contact_type'] == null ? undefined : json['contact_type'],
        'department': json['department'] == null ? undefined : json['department'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function CreateContactRequestToJSON(json: any): CreateContactRequest {
    return CreateContactRequestToJSONTyped(json, false);
}

export function CreateContactRequestToJSONTyped(value?: CreateContactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'company': value['company'],
        'notes': value['notes'],
        'contact_type': value['contactType'],
        'department': value['department'],
        'role': value['role'],
    };
}

