/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCalendarRequest
 */
export interface CreateCalendarRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCalendarRequest
     */
    description?: string;
    /**
     * 
     * @type {CreateCalendarRequestVisibilityEnum}
     * @memberof CreateCalendarRequest
     */
    visibility?: CreateCalendarRequestVisibilityEnum;
}


/**
 * @export
 */
export const CreateCalendarRequestVisibilityEnum = {
    Private: 'private',
    Tenant: 'tenant'
} as const;
export type CreateCalendarRequestVisibilityEnum = typeof CreateCalendarRequestVisibilityEnum[keyof typeof CreateCalendarRequestVisibilityEnum];


/**
 * Check if a given object implements the CreateCalendarRequest interface.
 */
export function instanceOfCreateCalendarRequest(value: object): value is CreateCalendarRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateCalendarRequestFromJSON(json: any): CreateCalendarRequest {
    return CreateCalendarRequestFromJSONTyped(json, false);
}

export function CreateCalendarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCalendarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'description': json['description'] == null ? undefined : json['description'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
    };
}

export function CreateCalendarRequestToJSON(json: any): CreateCalendarRequest {
    return CreateCalendarRequestToJSONTyped(json, false);
}

export function CreateCalendarRequestToJSONTyped(value?: CreateCalendarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'owner_email': value['ownerEmail'],
        'description': value['description'],
        'visibility': value['visibility'],
    };
}

