/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DedicatedIPRequest
 */
export interface DedicatedIPRequest {
    /**
     * 
     * @type {string}
     * @memberof DedicatedIPRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DedicatedIPRequest
     */
    tenantId: string;
    /**
     * 
     * @type {DedicatedIPRequestStatusEnum}
     * @memberof DedicatedIPRequest
     */
    status: DedicatedIPRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DedicatedIPRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof DedicatedIPRequest
     */
    adminNote?: string;
    /**
     * 
     * @type {Date}
     * @memberof DedicatedIPRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DedicatedIPRequest
     */
    resolvedAt?: Date;
}


/**
 * @export
 */
export const DedicatedIPRequestStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type DedicatedIPRequestStatusEnum = typeof DedicatedIPRequestStatusEnum[keyof typeof DedicatedIPRequestStatusEnum];


/**
 * Check if a given object implements the DedicatedIPRequest interface.
 */
export function instanceOfDedicatedIPRequest(value: object): value is DedicatedIPRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function DedicatedIPRequestFromJSON(json: any): DedicatedIPRequest {
    return DedicatedIPRequestFromJSONTyped(json, false);
}

export function DedicatedIPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DedicatedIPRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'status': json['status'],
        'note': json['note'] == null ? undefined : json['note'],
        'adminNote': json['admin_note'] == null ? undefined : json['admin_note'],
        'createdAt': (new Date(json['created_at'])),
        'resolvedAt': json['resolved_at'] == null ? undefined : (new Date(json['resolved_at'])),
    };
}

export function DedicatedIPRequestToJSON(json: any): DedicatedIPRequest {
    return DedicatedIPRequestToJSONTyped(json, false);
}

export function DedicatedIPRequestToJSONTyped(value?: DedicatedIPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'status': value['status'],
        'note': value['note'],
        'admin_note': value['adminNote'],
        'created_at': value['createdAt'].toISOString(),
        'resolved_at': value['resolvedAt'] == null ? value['resolvedAt'] : value['resolvedAt'].toISOString(),
    };
}

