/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DistributionListSummary
 */
export interface DistributionListSummary {
    /**
     * 
     * @type {string}
     * @memberof DistributionListSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DistributionListSummary
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof DistributionListSummary
     */
    listAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DistributionListSummary
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof DistributionListSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof DistributionListSummary
     */
    memberCount: number;
}

/**
 * Check if a given object implements the DistributionListSummary interface.
 */
export function instanceOfDistributionListSummary(value: object): value is DistributionListSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('listAddress' in value) && !('list_address' in value)) || (value['listAddress'] === undefined && value['list_address'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('memberCount' in value) && !('member_count' in value)) || (value['memberCount'] === undefined && value['member_count'] === undefined)) return false;
    return true;
}

export function DistributionListSummaryFromJSON(json: any): DistributionListSummary {
    return DistributionListSummaryFromJSONTyped(json, false);
}

export function DistributionListSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionListSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'listAddress': json['list_address'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': (new Date(json['created_at'])),
        'memberCount': json['member_count'],
    };
}

export function DistributionListSummaryToJSON(json: any): DistributionListSummary {
    return DistributionListSummaryToJSONTyped(json, false);
}

export function DistributionListSummaryToJSONTyped(value?: DistributionListSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'list_address': value['listAddress'],
        'name': value['name'],
        'created_at': value['createdAt'].toISOString(),
        'member_count': value['memberCount'],
    };
}

