/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DNSRecord
 */
export interface DNSRecord {
    /**
     * 
     * @type {DNSRecordTypeEnum}
     * @memberof DNSRecord
     */
    type: DNSRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DNSRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DNSRecord
     */
    value: string;
    /**
     * 
     * @type {number}
     * @memberof DNSRecord
     */
    ttl: number;
    /**
     * MX records only.
     * @type {number}
     * @memberof DNSRecord
     */
    priority?: number;
    /**
     * 
     * @type {DNSRecordPurposeEnum}
     * @memberof DNSRecord
     */
    purpose: DNSRecordPurposeEnum;
}


/**
 * @export
 */
export const DNSRecordTypeEnum = {
    Txt: 'TXT',
    Mx: 'MX'
} as const;
export type DNSRecordTypeEnum = typeof DNSRecordTypeEnum[keyof typeof DNSRecordTypeEnum];

/**
 * @export
 */
export const DNSRecordPurposeEnum = {
    Verification: 'verification',
    Spf: 'spf',
    Dkim: 'dkim',
    MxPrimary: 'mx-primary',
    MxBackup: 'mx-backup',
    Dmarc: 'dmarc'
} as const;
export type DNSRecordPurposeEnum = typeof DNSRecordPurposeEnum[keyof typeof DNSRecordPurposeEnum];


/**
 * Check if a given object implements the DNSRecord interface.
 */
export function instanceOfDNSRecord(value: object): value is DNSRecord {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('ttl' in value) || value['ttl'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    return true;
}

export function DNSRecordFromJSON(json: any): DNSRecord {
    return DNSRecordFromJSONTyped(json, false);
}

export function DNSRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): DNSRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'value': json['value'],
        'ttl': json['ttl'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'purpose': json['purpose'],
    };
}

export function DNSRecordToJSON(json: any): DNSRecord {
    return DNSRecordToJSONTyped(json, false);
}

export function DNSRecordToJSONTyped(value?: DNSRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'value': value['value'],
        'ttl': value['ttl'],
        'priority': value['priority'],
        'purpose': value['purpose'],
    };
}

