/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAddOnStatus200Response
 */
export interface GetAddOnStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAddOnStatus200Response
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetAddOnStatus200Response
     */
    eligible: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetAddOnStatus200Response
     */
    active: boolean;
}

/**
 * Check if a given object implements the GetAddOnStatus200Response interface.
 */
export function instanceOfGetAddOnStatus200Response(value: object): value is GetAddOnStatus200Response {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('eligible' in value) || value['eligible'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function GetAddOnStatus200ResponseFromJSON(json: any): GetAddOnStatus200Response {
    return GetAddOnStatus200ResponseFromJSONTyped(json, false);
}

export function GetAddOnStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAddOnStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'eligible': json['eligible'],
        'active': json['active'],
    };
}

export function GetAddOnStatus200ResponseToJSON(json: any): GetAddOnStatus200Response {
    return GetAddOnStatus200ResponseToJSONTyped(json, false);
}

export function GetAddOnStatus200ResponseToJSONTyped(value?: GetAddOnStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'eligible': value['eligible'],
        'active': value['active'],
    };
}

