/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetContactLists200ResponseDataInner
 */
export interface GetContactLists200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetContactLists200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContactLists200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContactLists200ResponseDataInner
     */
    visibility?: string;
}

/**
 * Check if a given object implements the GetContactLists200ResponseDataInner interface.
 */
export function instanceOfGetContactLists200ResponseDataInner(value: object): value is GetContactLists200ResponseDataInner {
    return true;
}

export function GetContactLists200ResponseDataInnerFromJSON(json: any): GetContactLists200ResponseDataInner {
    return GetContactLists200ResponseDataInnerFromJSONTyped(json, false);
}

export function GetContactLists200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetContactLists200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
    };
}

export function GetContactLists200ResponseDataInnerToJSON(json: any): GetContactLists200ResponseDataInner {
    return GetContactLists200ResponseDataInnerToJSONTyped(json, false);
}

export function GetContactLists200ResponseDataInnerToJSONTyped(value?: GetContactLists200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'visibility': value['visibility'],
    };
}

