/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCalendarSecurity200ResponseExternalSharing
 */
export interface GetCalendarSecurity200ResponseExternalSharing {
    /**
     * 
     * @type {boolean}
     * @memberof GetCalendarSecurity200ResponseExternalSharing
     */
    invitesAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCalendarSecurity200ResponseExternalSharing
     */
    sharingAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCalendarSecurity200ResponseExternalSharing
     */
    publicLinks?: boolean;
}

/**
 * Check if a given object implements the GetCalendarSecurity200ResponseExternalSharing interface.
 */
export function instanceOfGetCalendarSecurity200ResponseExternalSharing(value: object): value is GetCalendarSecurity200ResponseExternalSharing {
    return true;
}

export function GetCalendarSecurity200ResponseExternalSharingFromJSON(json: any): GetCalendarSecurity200ResponseExternalSharing {
    return GetCalendarSecurity200ResponseExternalSharingFromJSONTyped(json, false);
}

export function GetCalendarSecurity200ResponseExternalSharingFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCalendarSecurity200ResponseExternalSharing {
    if (json == null) {
        return json;
    }
    return {
        
        'invitesAllowed': json['invites_allowed'] == null ? undefined : json['invites_allowed'],
        'sharingAllowed': json['sharing_allowed'] == null ? undefined : json['sharing_allowed'],
        'publicLinks': json['public_links'] == null ? undefined : json['public_links'],
    };
}

export function GetCalendarSecurity200ResponseExternalSharingToJSON(json: any): GetCalendarSecurity200ResponseExternalSharing {
    return GetCalendarSecurity200ResponseExternalSharingToJSONTyped(json, false);
}

export function GetCalendarSecurity200ResponseExternalSharingToJSONTyped(value?: GetCalendarSecurity200ResponseExternalSharing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invites_allowed': value['invitesAllowed'],
        'sharing_allowed': value['sharingAllowed'],
        'public_links': value['publicLinks'],
    };
}

