/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCalendarSecurity200ResponseDelegatedAccessInner
 */
export interface GetCalendarSecurity200ResponseDelegatedAccessInner {
    /**
     * 
     * @type {string}
     * @memberof GetCalendarSecurity200ResponseDelegatedAccessInner
     */
    calendarId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCalendarSecurity200ResponseDelegatedAccessInner
     */
    calendarName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCalendarSecurity200ResponseDelegatedAccessInner
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCalendarSecurity200ResponseDelegatedAccessInner
     */
    role?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetCalendarSecurity200ResponseDelegatedAccessInner
     */
    grantedAt?: Date;
}

/**
 * Check if a given object implements the GetCalendarSecurity200ResponseDelegatedAccessInner interface.
 */
export function instanceOfGetCalendarSecurity200ResponseDelegatedAccessInner(value: object): value is GetCalendarSecurity200ResponseDelegatedAccessInner {
    return true;
}

export function GetCalendarSecurity200ResponseDelegatedAccessInnerFromJSON(json: any): GetCalendarSecurity200ResponseDelegatedAccessInner {
    return GetCalendarSecurity200ResponseDelegatedAccessInnerFromJSONTyped(json, false);
}

export function GetCalendarSecurity200ResponseDelegatedAccessInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCalendarSecurity200ResponseDelegatedAccessInner {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarId': json['calendar_id'] == null ? undefined : json['calendar_id'],
        'calendarName': json['calendar_name'] == null ? undefined : json['calendar_name'],
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'role': json['role'] == null ? undefined : json['role'],
        'grantedAt': json['granted_at'] == null ? undefined : (new Date(json['granted_at'])),
    };
}

export function GetCalendarSecurity200ResponseDelegatedAccessInnerToJSON(json: any): GetCalendarSecurity200ResponseDelegatedAccessInner {
    return GetCalendarSecurity200ResponseDelegatedAccessInnerToJSONTyped(json, false);
}

export function GetCalendarSecurity200ResponseDelegatedAccessInnerToJSONTyped(value?: GetCalendarSecurity200ResponseDelegatedAccessInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendar_id': value['calendarId'],
        'calendar_name': value['calendarName'],
        'user_email': value['userEmail'],
        'role': value['role'],
        'granted_at': value['grantedAt'] == null ? value['grantedAt'] : value['grantedAt'].toISOString(),
    };
}

