/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetContactLists200ResponseDataInner } from './GetContactLists200ResponseDataInner';
import {
    GetContactLists200ResponseDataInnerFromJSON,
    GetContactLists200ResponseDataInnerFromJSONTyped,
    GetContactLists200ResponseDataInnerToJSON,
    GetContactLists200ResponseDataInnerToJSONTyped,
} from './GetContactLists200ResponseDataInner';

/**
 * 
 * @export
 * @interface GetContactLists200Response
 */
export interface GetContactLists200Response {
    /**
     * 
     * @type {Array<GetContactLists200ResponseDataInner>}
     * @memberof GetContactLists200Response
     */
    data?: Array<GetContactLists200ResponseDataInner>;
}

/**
 * Check if a given object implements the GetContactLists200Response interface.
 */
export function instanceOfGetContactLists200Response(value: object): value is GetContactLists200Response {
    return true;
}

export function GetContactLists200ResponseFromJSON(json: any): GetContactLists200Response {
    return GetContactLists200ResponseFromJSONTyped(json, false);
}

export function GetContactLists200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetContactLists200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GetContactLists200ResponseDataInnerFromJSON)),
    };
}

export function GetContactLists200ResponseToJSON(json: any): GetContactLists200Response {
    return GetContactLists200ResponseToJSONTyped(json, false);
}

export function GetContactLists200ResponseToJSONTyped(value?: GetContactLists200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GetContactLists200ResponseDataInnerToJSON)),
    };
}

