/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetContactList200ResponseMembersInner
 */
export interface GetContactList200ResponseMembersInner {
    /**
     * 
     * @type {string}
     * @memberof GetContactList200ResponseMembersInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContactList200ResponseMembersInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContactList200ResponseMembersInner
     */
    email?: string;
}

/**
 * Check if a given object implements the GetContactList200ResponseMembersInner interface.
 */
export function instanceOfGetContactList200ResponseMembersInner(value: object): value is GetContactList200ResponseMembersInner {
    return true;
}

export function GetContactList200ResponseMembersInnerFromJSON(json: any): GetContactList200ResponseMembersInner {
    return GetContactList200ResponseMembersInnerFromJSONTyped(json, false);
}

export function GetContactList200ResponseMembersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetContactList200ResponseMembersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function GetContactList200ResponseMembersInnerToJSON(json: any): GetContactList200ResponseMembersInner {
    return GetContactList200ResponseMembersInnerToJSONTyped(json, false);
}

export function GetContactList200ResponseMembersInnerToJSONTyped(value?: GetContactList200ResponseMembersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

