/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetDomainsStatus200ResponseDomainsInner } from './GetDomainsStatus200ResponseDomainsInner';
import {
    GetDomainsStatus200ResponseDomainsInnerFromJSON,
    GetDomainsStatus200ResponseDomainsInnerFromJSONTyped,
    GetDomainsStatus200ResponseDomainsInnerToJSON,
    GetDomainsStatus200ResponseDomainsInnerToJSONTyped,
} from './GetDomainsStatus200ResponseDomainsInner';

/**
 * 
 * @export
 * @interface GetDomainsStatus200Response
 */
export interface GetDomainsStatus200Response {
    /**
     * 
     * @type {Array<GetDomainsStatus200ResponseDomainsInner>}
     * @memberof GetDomainsStatus200Response
     */
    domains?: Array<GetDomainsStatus200ResponseDomainsInner>;
    /**
     * 
     * @type {Date}
     * @memberof GetDomainsStatus200Response
     */
    generatedAt?: Date;
}

/**
 * Check if a given object implements the GetDomainsStatus200Response interface.
 */
export function instanceOfGetDomainsStatus200Response(value: object): value is GetDomainsStatus200Response {
    return true;
}

export function GetDomainsStatus200ResponseFromJSON(json: any): GetDomainsStatus200Response {
    return GetDomainsStatus200ResponseFromJSONTyped(json, false);
}

export function GetDomainsStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDomainsStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(GetDomainsStatus200ResponseDomainsInnerFromJSON)),
        'generatedAt': json['generated_at'] == null ? undefined : (new Date(json['generated_at'])),
    };
}

export function GetDomainsStatus200ResponseToJSON(json: any): GetDomainsStatus200Response {
    return GetDomainsStatus200ResponseToJSONTyped(json, false);
}

export function GetDomainsStatus200ResponseToJSONTyped(value?: GetDomainsStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(GetDomainsStatus200ResponseDomainsInnerToJSON)),
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : value['generatedAt'].toISOString(),
    };
}

