/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEncryptionKey200Response
 */
export interface GetEncryptionKey200Response {
    /**
     * 
     * @type {string}
     * @memberof GetEncryptionKey200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEncryptionKey200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEncryptionKey200Response
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEncryptionKey200Response
     */
    encryptedPrivateKey?: string;
    /**
     * 
     * @type {object}
     * @memberof GetEncryptionKey200Response
     */
    kdfParams?: object;
    /**
     * 
     * @type {number}
     * @memberof GetEncryptionKey200Response
     */
    version?: number;
}

/**
 * Check if a given object implements the GetEncryptionKey200Response interface.
 */
export function instanceOfGetEncryptionKey200Response(value: object): value is GetEncryptionKey200Response {
    return true;
}

export function GetEncryptionKey200ResponseFromJSON(json: any): GetEncryptionKey200Response {
    return GetEncryptionKey200ResponseFromJSONTyped(json, false);
}

export function GetEncryptionKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncryptionKey200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'encryptedPrivateKey': json['encrypted_private_key'] == null ? undefined : json['encrypted_private_key'],
        'kdfParams': json['kdf_params'] == null ? undefined : json['kdf_params'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function GetEncryptionKey200ResponseToJSON(json: any): GetEncryptionKey200Response {
    return GetEncryptionKey200ResponseToJSONTyped(json, false);
}

export function GetEncryptionKey200ResponseToJSONTyped(value?: GetEncryptionKey200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'public_key': value['publicKey'],
        'encrypted_private_key': value['encryptedPrivateKey'],
        'kdf_params': value['kdfParams'],
        'version': value['version'],
    };
}

