/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetIntegrationsSummary200ResponseApiKeysInner } from './GetIntegrationsSummary200ResponseApiKeysInner';
import {
    GetIntegrationsSummary200ResponseApiKeysInnerFromJSON,
    GetIntegrationsSummary200ResponseApiKeysInnerFromJSONTyped,
    GetIntegrationsSummary200ResponseApiKeysInnerToJSON,
    GetIntegrationsSummary200ResponseApiKeysInnerToJSONTyped,
} from './GetIntegrationsSummary200ResponseApiKeysInner';
import type { GetIntegrationsSummary200ResponseWebhooksInner } from './GetIntegrationsSummary200ResponseWebhooksInner';
import {
    GetIntegrationsSummary200ResponseWebhooksInnerFromJSON,
    GetIntegrationsSummary200ResponseWebhooksInnerFromJSONTyped,
    GetIntegrationsSummary200ResponseWebhooksInnerToJSON,
    GetIntegrationsSummary200ResponseWebhooksInnerToJSONTyped,
} from './GetIntegrationsSummary200ResponseWebhooksInner';

/**
 * 
 * @export
 * @interface GetIntegrationsSummary200Response
 */
export interface GetIntegrationsSummary200Response {
    /**
     * 
     * @type {number}
     * @memberof GetIntegrationsSummary200Response
     */
    apiRequestsToday?: number;
    /**
     * 
     * @type {number}
     * @memberof GetIntegrationsSummary200Response
     */
    activeApiKeys?: number;
    /**
     * 
     * @type {Array<GetIntegrationsSummary200ResponseApiKeysInner>}
     * @memberof GetIntegrationsSummary200Response
     */
    apiKeys?: Array<GetIntegrationsSummary200ResponseApiKeysInner>;
    /**
     * 
     * @type {number}
     * @memberof GetIntegrationsSummary200Response
     */
    webhookFailures?: number;
    /**
     * 
     * @type {number}
     * @memberof GetIntegrationsSummary200Response
     */
    webhooksTotal?: number;
    /**
     * 
     * @type {Array<GetIntegrationsSummary200ResponseWebhooksInner>}
     * @memberof GetIntegrationsSummary200Response
     */
    webhooks?: Array<GetIntegrationsSummary200ResponseWebhooksInner>;
    /**
     * 
     * @type {Date}
     * @memberof GetIntegrationsSummary200Response
     */
    generatedAt?: Date;
}

/**
 * Check if a given object implements the GetIntegrationsSummary200Response interface.
 */
export function instanceOfGetIntegrationsSummary200Response(value: object): value is GetIntegrationsSummary200Response {
    return true;
}

export function GetIntegrationsSummary200ResponseFromJSON(json: any): GetIntegrationsSummary200Response {
    return GetIntegrationsSummary200ResponseFromJSONTyped(json, false);
}

export function GetIntegrationsSummary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIntegrationsSummary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'apiRequestsToday': json['api_requests_today'] == null ? undefined : json['api_requests_today'],
        'activeApiKeys': json['active_api_keys'] == null ? undefined : json['active_api_keys'],
        'apiKeys': json['api_keys'] == null ? undefined : ((json['api_keys'] as Array<any>).map(GetIntegrationsSummary200ResponseApiKeysInnerFromJSON)),
        'webhookFailures': json['webhook_failures'] == null ? undefined : json['webhook_failures'],
        'webhooksTotal': json['webhooks_total'] == null ? undefined : json['webhooks_total'],
        'webhooks': json['webhooks'] == null ? undefined : ((json['webhooks'] as Array<any>).map(GetIntegrationsSummary200ResponseWebhooksInnerFromJSON)),
        'generatedAt': json['generated_at'] == null ? undefined : (new Date(json['generated_at'])),
    };
}

export function GetIntegrationsSummary200ResponseToJSON(json: any): GetIntegrationsSummary200Response {
    return GetIntegrationsSummary200ResponseToJSONTyped(json, false);
}

export function GetIntegrationsSummary200ResponseToJSONTyped(value?: GetIntegrationsSummary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_requests_today': value['apiRequestsToday'],
        'active_api_keys': value['activeApiKeys'],
        'api_keys': value['apiKeys'] == null ? undefined : ((value['apiKeys'] as Array<any>).map(GetIntegrationsSummary200ResponseApiKeysInnerToJSON)),
        'webhook_failures': value['webhookFailures'],
        'webhooks_total': value['webhooksTotal'],
        'webhooks': value['webhooks'] == null ? undefined : ((value['webhooks'] as Array<any>).map(GetIntegrationsSummary200ResponseWebhooksInnerToJSON)),
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : value['generatedAt'].toISOString(),
    };
}

