/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIPAssignment200Response
 */
export interface GetIPAssignment200Response {
    /**
     * 
     * @type {string}
     * @memberof GetIPAssignment200Response
     */
    poolName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIPAssignment200Response
     */
    poolKind?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIPAssignment200Response
     */
    dedicatedIp?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetIPAssignment200Response
     */
    assignedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetIPAssignment200Response
     */
    reason?: string;
}

/**
 * Check if a given object implements the GetIPAssignment200Response interface.
 */
export function instanceOfGetIPAssignment200Response(value: object): value is GetIPAssignment200Response {
    return true;
}

export function GetIPAssignment200ResponseFromJSON(json: any): GetIPAssignment200Response {
    return GetIPAssignment200ResponseFromJSONTyped(json, false);
}

export function GetIPAssignment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIPAssignment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'poolName': json['pool_name'] == null ? undefined : json['pool_name'],
        'poolKind': json['pool_kind'] == null ? undefined : json['pool_kind'],
        'dedicatedIp': json['dedicated_ip'] == null ? undefined : json['dedicated_ip'],
        'assignedAt': json['assigned_at'] == null ? undefined : (new Date(json['assigned_at'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function GetIPAssignment200ResponseToJSON(json: any): GetIPAssignment200Response {
    return GetIPAssignment200ResponseToJSONTyped(json, false);
}

export function GetIPAssignment200ResponseToJSONTyped(value?: GetIPAssignment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool_name': value['poolName'],
        'pool_kind': value['poolKind'],
        'dedicated_ip': value['dedicatedIp'],
        'assigned_at': value['assignedAt'] == null ? value['assignedAt'] : value['assignedAt'].toISOString(),
        'reason': value['reason'],
    };
}

