/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetIntegrationsSummary200ResponseWebhooksInner
 */
export interface GetIntegrationsSummary200ResponseWebhooksInner {
    /**
     * 
     * @type {string}
     * @memberof GetIntegrationsSummary200ResponseWebhooksInner
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetIntegrationsSummary200ResponseWebhooksInner
     */
    paused?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetIntegrationsSummary200ResponseWebhooksInner
     */
    consecutiveFailures?: number;
    /**
     * 
     * @type {Date}
     * @memberof GetIntegrationsSummary200ResponseWebhooksInner
     */
    lastFailureAt?: Date;
}

/**
 * Check if a given object implements the GetIntegrationsSummary200ResponseWebhooksInner interface.
 */
export function instanceOfGetIntegrationsSummary200ResponseWebhooksInner(value: object): value is GetIntegrationsSummary200ResponseWebhooksInner {
    return true;
}

export function GetIntegrationsSummary200ResponseWebhooksInnerFromJSON(json: any): GetIntegrationsSummary200ResponseWebhooksInner {
    return GetIntegrationsSummary200ResponseWebhooksInnerFromJSONTyped(json, false);
}

export function GetIntegrationsSummary200ResponseWebhooksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIntegrationsSummary200ResponseWebhooksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'paused': json['paused'] == null ? undefined : json['paused'],
        'consecutiveFailures': json['consecutive_failures'] == null ? undefined : json['consecutive_failures'],
        'lastFailureAt': json['last_failure_at'] == null ? undefined : (new Date(json['last_failure_at'])),
    };
}

export function GetIntegrationsSummary200ResponseWebhooksInnerToJSON(json: any): GetIntegrationsSummary200ResponseWebhooksInner {
    return GetIntegrationsSummary200ResponseWebhooksInnerToJSONTyped(json, false);
}

export function GetIntegrationsSummary200ResponseWebhooksInnerToJSONTyped(value?: GetIntegrationsSummary200ResponseWebhooksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'paused': value['paused'],
        'consecutive_failures': value['consecutiveFailures'],
        'last_failure_at': value['lastFailureAt'] == null ? value['lastFailureAt'] : value['lastFailureAt'].toISOString(),
    };
}

