/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSecurity200ResponseAlertsInner
 */
export interface GetSecurity200ResponseAlertsInner {
    /**
     * 
     * @type {GetSecurity200ResponseAlertsInnerLevelEnum}
     * @memberof GetSecurity200ResponseAlertsInner
     */
    level?: GetSecurity200ResponseAlertsInnerLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof GetSecurity200ResponseAlertsInner
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetSecurity200ResponseAlertsInner
     */
    time?: Date;
}


/**
 * @export
 */
export const GetSecurity200ResponseAlertsInnerLevelEnum = {
    Info: 'info',
    Warning: 'warning',
    Critical: 'critical'
} as const;
export type GetSecurity200ResponseAlertsInnerLevelEnum = typeof GetSecurity200ResponseAlertsInnerLevelEnum[keyof typeof GetSecurity200ResponseAlertsInnerLevelEnum];


/**
 * Check if a given object implements the GetSecurity200ResponseAlertsInner interface.
 */
export function instanceOfGetSecurity200ResponseAlertsInner(value: object): value is GetSecurity200ResponseAlertsInner {
    return true;
}

export function GetSecurity200ResponseAlertsInnerFromJSON(json: any): GetSecurity200ResponseAlertsInner {
    return GetSecurity200ResponseAlertsInnerFromJSONTyped(json, false);
}

export function GetSecurity200ResponseAlertsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSecurity200ResponseAlertsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'message': json['message'] == null ? undefined : json['message'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
    };
}

export function GetSecurity200ResponseAlertsInnerToJSON(json: any): GetSecurity200ResponseAlertsInner {
    return GetSecurity200ResponseAlertsInnerToJSONTyped(json, false);
}

export function GetSecurity200ResponseAlertsInnerToJSONTyped(value?: GetSecurity200ResponseAlertsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'message': value['message'],
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
    };
}

