/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserEvent } from './UserEvent';
import {
    UserEventFromJSON,
    UserEventFromJSONTyped,
    UserEventToJSON,
    UserEventToJSONTyped,
} from './UserEvent';

/**
 * 
 * @export
 * @interface GetUserInsights200Response
 */
export interface GetUserInsights200Response {
    /**
     * 
     * @type {Array<UserEvent>}
     * @memberof GetUserInsights200Response
     */
    recentlyAdded?: Array<UserEvent>;
    /**
     * 
     * @type {Array<UserEvent>}
     * @memberof GetUserInsights200Response
     */
    recentlySuspended?: Array<UserEvent>;
    /**
     * 
     * @type {Array<UserEvent>}
     * @memberof GetUserInsights200Response
     */
    inactive30d?: Array<UserEvent>;
    /**
     * 
     * @type {number}
     * @memberof GetUserInsights200Response
     */
    seatsUsed?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserInsights200Response
     */
    seatsAlloc?: number;
    /**
     * True only on tiers with a hard seat cap (Free, Founder). On unlimited/per-seat tiers seats_alloc merely tracks the live mailbox count, so seats_used == seats_alloc is normal and must not be read as 'at capacity'.
     * @type {boolean}
     * @memberof GetUserInsights200Response
     */
    seatsCapped?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetUserInsights200Response
     */
    generatedAt?: Date;
}

/**
 * Check if a given object implements the GetUserInsights200Response interface.
 */
export function instanceOfGetUserInsights200Response(value: object): value is GetUserInsights200Response {
    return true;
}

export function GetUserInsights200ResponseFromJSON(json: any): GetUserInsights200Response {
    return GetUserInsights200ResponseFromJSONTyped(json, false);
}

export function GetUserInsights200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInsights200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'recentlyAdded': json['recently_added'] == null ? undefined : ((json['recently_added'] as Array<any>).map(UserEventFromJSON)),
        'recentlySuspended': json['recently_suspended'] == null ? undefined : ((json['recently_suspended'] as Array<any>).map(UserEventFromJSON)),
        'inactive30d': json['inactive_30d'] == null ? undefined : ((json['inactive_30d'] as Array<any>).map(UserEventFromJSON)),
        'seatsUsed': json['seats_used'] == null ? undefined : json['seats_used'],
        'seatsAlloc': json['seats_alloc'] == null ? undefined : json['seats_alloc'],
        'seatsCapped': json['seats_capped'] == null ? undefined : json['seats_capped'],
        'generatedAt': json['generated_at'] == null ? undefined : (new Date(json['generated_at'])),
    };
}

export function GetUserInsights200ResponseToJSON(json: any): GetUserInsights200Response {
    return GetUserInsights200ResponseToJSONTyped(json, false);
}

export function GetUserInsights200ResponseToJSONTyped(value?: GetUserInsights200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recently_added': value['recentlyAdded'] == null ? undefined : ((value['recentlyAdded'] as Array<any>).map(UserEventToJSON)),
        'recently_suspended': value['recentlySuspended'] == null ? undefined : ((value['recentlySuspended'] as Array<any>).map(UserEventToJSON)),
        'inactive_30d': value['inactive30d'] == null ? undefined : ((value['inactive30d'] as Array<any>).map(UserEventToJSON)),
        'seats_used': value['seatsUsed'],
        'seats_alloc': value['seatsAlloc'],
        'seats_capped': value['seatsCapped'],
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : value['generatedAt'].toISOString(),
    };
}

