/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrationCredential } from './MigrationCredential';
import {
    MigrationCredentialFromJSON,
    MigrationCredentialFromJSONTyped,
    MigrationCredentialToJSON,
    MigrationCredentialToJSONTyped,
} from './MigrationCredential';

/**
 * 
 * @export
 * @interface ListMigrationCredentials200Response
 */
export interface ListMigrationCredentials200Response {
    /**
     * 
     * @type {Array<MigrationCredential>}
     * @memberof ListMigrationCredentials200Response
     */
    data: Array<MigrationCredential>;
}

/**
 * Check if a given object implements the ListMigrationCredentials200Response interface.
 */
export function instanceOfListMigrationCredentials200Response(value: object): value is ListMigrationCredentials200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListMigrationCredentials200ResponseFromJSON(json: any): ListMigrationCredentials200Response {
    return ListMigrationCredentials200ResponseFromJSONTyped(json, false);
}

export function ListMigrationCredentials200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMigrationCredentials200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(MigrationCredentialFromJSON)),
    };
}

export function ListMigrationCredentials200ResponseToJSON(json: any): ListMigrationCredentials200Response {
    return ListMigrationCredentials200ResponseToJSONTyped(json, false);
}

export function ListMigrationCredentials200ResponseToJSONTyped(value?: ListMigrationCredentials200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(MigrationCredentialToJSON)),
    };
}

