/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrationEvent } from './MigrationEvent';
import {
    MigrationEventFromJSON,
    MigrationEventFromJSONTyped,
    MigrationEventToJSON,
    MigrationEventToJSONTyped,
} from './MigrationEvent';

/**
 * 
 * @export
 * @interface ListMigrationEvents200Response
 */
export interface ListMigrationEvents200Response {
    /**
     * 
     * @type {Array<MigrationEvent>}
     * @memberof ListMigrationEvents200Response
     */
    data: Array<MigrationEvent>;
}

/**
 * Check if a given object implements the ListMigrationEvents200Response interface.
 */
export function instanceOfListMigrationEvents200Response(value: object): value is ListMigrationEvents200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListMigrationEvents200ResponseFromJSON(json: any): ListMigrationEvents200Response {
    return ListMigrationEvents200ResponseFromJSONTyped(json, false);
}

export function ListMigrationEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMigrationEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(MigrationEventFromJSON)),
    };
}

export function ListMigrationEvents200ResponseToJSON(json: any): ListMigrationEvents200Response {
    return ListMigrationEvents200ResponseToJSONTyped(json, false);
}

export function ListMigrationEvents200ResponseToJSONTyped(value?: ListMigrationEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(MigrationEventToJSON)),
    };
}

