/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ListUsers200Response
 */
export interface ListUsers200Response {
    /**
     * 
     * @type {Array<User>}
     * @memberof ListUsers200Response
     */
    data: Array<User>;
    /**
     * 
     * @type {number}
     * @memberof ListUsers200Response
     */
    limit: number;
}

/**
 * Check if a given object implements the ListUsers200Response interface.
 */
export function instanceOfListUsers200Response(value: object): value is ListUsers200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ListUsers200ResponseFromJSON(json: any): ListUsers200Response {
    return ListUsers200ResponseFromJSONTyped(json, false);
}

export function ListUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserFromJSON)),
        'limit': json['limit'],
    };
}

export function ListUsers200ResponseToJSON(json: any): ListUsers200Response {
    return ListUsers200ResponseToJSONTyped(json, false);
}

export function ListUsers200ResponseToJSONTyped(value?: ListUsers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserToJSON)),
        'limit': value['limit'],
    };
}

