/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Mailbox
 */
export interface Mailbox {
    /**
     * 
     * @type {string}
     * @memberof Mailbox
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Mailbox
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Mailbox
     */
    domainId: string;
    /**
     * 
     * @type {string}
     * @memberof Mailbox
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof Mailbox
     */
    quotaBytes: number;
    /**
     * 
     * @type {boolean}
     * @memberof Mailbox
     */
    disabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Mailbox
     */
    disabledAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Mailbox
     */
    softDeletedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Mailbox
     */
    hardDeleteAfter?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Mailbox
     */
    createdAt: Date;
    /**
     * ONLY present on POST response when lockally generated the password. Shown once.
     * @type {string}
     * @memberof Mailbox
     */
    password?: string;
}

/**
 * Check if a given object implements the Mailbox interface.
 */
export function instanceOfMailbox(value: object): value is Mailbox {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('domainId' in value) && !('domain_id' in value)) || (value['domainId'] === undefined && value['domain_id'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if ((!('quotaBytes' in value) && !('quota_bytes' in value)) || (value['quotaBytes'] === undefined && value['quota_bytes'] === undefined)) return false;
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function MailboxFromJSON(json: any): Mailbox {
    return MailboxFromJSONTyped(json, false);
}

export function MailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mailbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'domainId': json['domain_id'],
        'email': json['email'],
        'quotaBytes': json['quota_bytes'],
        'disabled': json['disabled'],
        'disabledAt': json['disabled_at'] == null ? undefined : (new Date(json['disabled_at'])),
        'softDeletedAt': json['soft_deleted_at'] == null ? undefined : (new Date(json['soft_deleted_at'])),
        'hardDeleteAfter': json['hard_delete_after'] == null ? undefined : (new Date(json['hard_delete_after'])),
        'createdAt': (new Date(json['created_at'])),
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function MailboxToJSON(json: any): Mailbox {
    return MailboxToJSONTyped(json, false);
}

export function MailboxToJSONTyped(value?: Mailbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'domain_id': value['domainId'],
        'email': value['email'],
        'quota_bytes': value['quotaBytes'],
        'disabled': value['disabled'],
        'disabled_at': value['disabledAt'] == null ? value['disabledAt'] : value['disabledAt'].toISOString(),
        'soft_deleted_at': value['softDeletedAt'] == null ? value['softDeletedAt'] : value['softDeletedAt'].toISOString(),
        'hard_delete_after': value['hardDeleteAfter'] == null ? value['hardDeleteAfter'] : value['hardDeleteAfter'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'password': value['password'],
    };
}

