/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapMigrationRequestMappingsInner
 */
export interface MapMigrationRequestMappingsInner {
    /**
     * 
     * @type {string}
     * @memberof MapMigrationRequestMappingsInner
     */
    sourceEmail: string;
    /**
     * 
     * @type {string}
     * @memberof MapMigrationRequestMappingsInner
     */
    destEmail: string;
}

/**
 * Check if a given object implements the MapMigrationRequestMappingsInner interface.
 */
export function instanceOfMapMigrationRequestMappingsInner(value: object): value is MapMigrationRequestMappingsInner {
    if ((!('sourceEmail' in value) && !('source_email' in value)) || (value['sourceEmail'] === undefined && value['source_email'] === undefined)) return false;
    if ((!('destEmail' in value) && !('dest_email' in value)) || (value['destEmail'] === undefined && value['dest_email'] === undefined)) return false;
    return true;
}

export function MapMigrationRequestMappingsInnerFromJSON(json: any): MapMigrationRequestMappingsInner {
    return MapMigrationRequestMappingsInnerFromJSONTyped(json, false);
}

export function MapMigrationRequestMappingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapMigrationRequestMappingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceEmail': json['source_email'],
        'destEmail': json['dest_email'],
    };
}

export function MapMigrationRequestMappingsInnerToJSON(json: any): MapMigrationRequestMappingsInner {
    return MapMigrationRequestMappingsInnerToJSONTyped(json, false);
}

export function MapMigrationRequestMappingsInnerToJSONTyped(value?: MapMigrationRequestMappingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_email': value['sourceEmail'],
        'dest_email': value['destEmail'],
    };
}

