/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single message with the content captured at send time. Returned only by GET /v1/messages/{id} (the list stays summary-only). Attachments are not returned.
 * 
 * @export
 * @interface MessageDetail
 */
export interface MessageDetail {
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    tenantId: string;
    /**
     * RFC 5322 Message-ID header, including angle brackets.
     * @type {string}
     * @memberof MessageDetail
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    sender: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageDetail
     */
    recipients: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    subject?: string;
    /**
     * 
     * @type {MessageDetailStatusEnum}
     * @memberof MessageDetail
     */
    status: MessageDetailStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof MessageDetail
     */
    queuedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MessageDetail
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    bounceReason?: string;
    /**
     * 
     * @type {number}
     * @memberof MessageDetail
     */
    sizeBytes?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    from?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageDetail
     */
    to?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageDetail
     */
    cc?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageDetail
     */
    bcc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDetail
     */
    html?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MessageDetail
     */
    headers?: { [key: string]: string; };
}


/**
 * @export
 */
export const MessageDetailStatusEnum = {
    Queued: 'queued',
    Sending: 'sending',
    Delivered: 'delivered',
    Bounced: 'bounced',
    Deferred: 'deferred',
    Complaint: 'complaint'
} as const;
export type MessageDetailStatusEnum = typeof MessageDetailStatusEnum[keyof typeof MessageDetailStatusEnum];


/**
 * Check if a given object implements the MessageDetail interface.
 */
export function instanceOfMessageDetail(value: object): value is MessageDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('messageId' in value) && !('message_id' in value)) || (value['messageId'] === undefined && value['message_id'] === undefined)) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('queuedAt' in value) && !('queued_at' in value)) || (value['queuedAt'] === undefined && value['queued_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function MessageDetailFromJSON(json: any): MessageDetail {
    return MessageDetailFromJSONTyped(json, false);
}

export function MessageDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'messageId': json['message_id'],
        'sender': json['sender'],
        'recipients': json['recipients'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'status': json['status'],
        'queuedAt': (new Date(json['queued_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'bounceReason': json['bounce_reason'] == null ? undefined : json['bounce_reason'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
        'cc': json['cc'] == null ? undefined : json['cc'],
        'bcc': json['bcc'] == null ? undefined : json['bcc'],
        'text': json['text'] == null ? undefined : json['text'],
        'html': json['html'] == null ? undefined : json['html'],
        'headers': json['headers'] == null ? undefined : json['headers'],
    };
}

export function MessageDetailToJSON(json: any): MessageDetail {
    return MessageDetailToJSONTyped(json, false);
}

export function MessageDetailToJSONTyped(value?: MessageDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'message_id': value['messageId'],
        'sender': value['sender'],
        'recipients': value['recipients'],
        'subject': value['subject'],
        'status': value['status'],
        'queued_at': value['queuedAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'bounce_reason': value['bounceReason'],
        'size_bytes': value['sizeBytes'],
        'from': value['from'],
        'to': value['to'],
        'cc': value['cc'],
        'bcc': value['bcc'],
        'text': value['text'],
        'html': value['html'],
        'headers': value['headers'],
    };
}

