/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MigrationSettings
 */
export interface MigrationSettings {
    /**
     * 
     * @type {number}
     * @memberof MigrationSettings
     */
    maxConcurrentMailboxes?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationSettings
     */
    maxConcurrentMessages?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationSettings
     */
    sourceRateLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationSettings
     */
    batchSize?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MigrationSettings
     */
    skipFolders?: Array<string>;
}

/**
 * Check if a given object implements the MigrationSettings interface.
 */
export function instanceOfMigrationSettings(value: object): value is MigrationSettings {
    return true;
}

export function MigrationSettingsFromJSON(json: any): MigrationSettings {
    return MigrationSettingsFromJSONTyped(json, false);
}

export function MigrationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'maxConcurrentMailboxes': json['max_concurrent_mailboxes'] == null ? undefined : json['max_concurrent_mailboxes'],
        'maxConcurrentMessages': json['max_concurrent_messages'] == null ? undefined : json['max_concurrent_messages'],
        'sourceRateLimit': json['source_rate_limit'] == null ? undefined : json['source_rate_limit'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'skipFolders': json['skip_folders'] == null ? undefined : json['skip_folders'],
    };
}

export function MigrationSettingsToJSON(json: any): MigrationSettings {
    return MigrationSettingsToJSONTyped(json, false);
}

export function MigrationSettingsToJSONTyped(value?: MigrationSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_concurrent_mailboxes': value['maxConcurrentMailboxes'],
        'max_concurrent_messages': value['maxConcurrentMessages'],
        'source_rate_limit': value['sourceRateLimit'],
        'batch_size': value['batchSize'],
        'skip_folders': value['skipFolders'],
    };
}

