/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrationProgressMailboxesInner } from './MigrationProgressMailboxesInner';
import {
    MigrationProgressMailboxesInnerFromJSON,
    MigrationProgressMailboxesInnerFromJSONTyped,
    MigrationProgressMailboxesInnerToJSON,
    MigrationProgressMailboxesInnerToJSONTyped,
} from './MigrationProgressMailboxesInner';

/**
 * 
 * @export
 * @interface MigrationProgress
 */
export interface MigrationProgress {
    /**
     * 
     * @type {string}
     * @memberof MigrationProgress
     */
    migrationId: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationProgress
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    totalMailboxes: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    completedMailboxes: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    failedMailboxes: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    totalMessages: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    syncedMessages: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    failedMessages: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationProgress
     */
    percentComplete: number;
    /**
     * 
     * @type {Array<MigrationProgressMailboxesInner>}
     * @memberof MigrationProgress
     */
    mailboxes: Array<MigrationProgressMailboxesInner>;
}

/**
 * Check if a given object implements the MigrationProgress interface.
 */
export function instanceOfMigrationProgress(value: object): value is MigrationProgress {
    if ((!('migrationId' in value) && !('migration_id' in value)) || (value['migrationId'] === undefined && value['migration_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('totalMailboxes' in value) && !('total_mailboxes' in value)) || (value['totalMailboxes'] === undefined && value['total_mailboxes'] === undefined)) return false;
    if ((!('completedMailboxes' in value) && !('completed_mailboxes' in value)) || (value['completedMailboxes'] === undefined && value['completed_mailboxes'] === undefined)) return false;
    if ((!('failedMailboxes' in value) && !('failed_mailboxes' in value)) || (value['failedMailboxes'] === undefined && value['failed_mailboxes'] === undefined)) return false;
    if ((!('totalMessages' in value) && !('total_messages' in value)) || (value['totalMessages'] === undefined && value['total_messages'] === undefined)) return false;
    if ((!('syncedMessages' in value) && !('synced_messages' in value)) || (value['syncedMessages'] === undefined && value['synced_messages'] === undefined)) return false;
    if ((!('failedMessages' in value) && !('failed_messages' in value)) || (value['failedMessages'] === undefined && value['failed_messages'] === undefined)) return false;
    if ((!('percentComplete' in value) && !('percent_complete' in value)) || (value['percentComplete'] === undefined && value['percent_complete'] === undefined)) return false;
    if (!('mailboxes' in value) || value['mailboxes'] === undefined) return false;
    return true;
}

export function MigrationProgressFromJSON(json: any): MigrationProgress {
    return MigrationProgressFromJSONTyped(json, false);
}

export function MigrationProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'migrationId': json['migration_id'],
        'status': json['status'],
        'totalMailboxes': json['total_mailboxes'],
        'completedMailboxes': json['completed_mailboxes'],
        'failedMailboxes': json['failed_mailboxes'],
        'totalMessages': json['total_messages'],
        'syncedMessages': json['synced_messages'],
        'failedMessages': json['failed_messages'],
        'percentComplete': json['percent_complete'],
        'mailboxes': ((json['mailboxes'] as Array<any>).map(MigrationProgressMailboxesInnerFromJSON)),
    };
}

export function MigrationProgressToJSON(json: any): MigrationProgress {
    return MigrationProgressToJSONTyped(json, false);
}

export function MigrationProgressToJSONTyped(value?: MigrationProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'migration_id': value['migrationId'],
        'status': value['status'],
        'total_mailboxes': value['totalMailboxes'],
        'completed_mailboxes': value['completedMailboxes'],
        'failed_mailboxes': value['failedMailboxes'],
        'total_messages': value['totalMessages'],
        'synced_messages': value['syncedMessages'],
        'failed_messages': value['failedMessages'],
        'percent_complete': value['percentComplete'],
        'mailboxes': ((value['mailboxes'] as Array<any>).map(MigrationProgressMailboxesInnerToJSON)),
    };
}

