/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MigrationMailbox
 */
export interface MigrationMailbox {
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    migrationId: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    sourceEmail: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    destEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    destMailboxId?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof MigrationMailbox
     */
    sourceMessageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationMailbox
     */
    syncedMessageCount: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationMailbox
     */
    failedMessageCount: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationMailbox
     */
    sourceSizeBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrationMailbox
     */
    syncedSizeBytes?: number;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    lastSyncedUid?: string;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMailbox
     */
    lastSyncedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MigrationMailbox
     */
    errorMessage?: string;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMailbox
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMailbox
     */
    completedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMailbox
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMailbox
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the MigrationMailbox interface.
 */
export function instanceOfMigrationMailbox(value: object): value is MigrationMailbox {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('migrationId' in value) && !('migration_id' in value)) || (value['migrationId'] === undefined && value['migration_id'] === undefined)) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('sourceEmail' in value) && !('source_email' in value)) || (value['sourceEmail'] === undefined && value['source_email'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('syncedMessageCount' in value) && !('synced_message_count' in value)) || (value['syncedMessageCount'] === undefined && value['synced_message_count'] === undefined)) return false;
    if ((!('failedMessageCount' in value) && !('failed_message_count' in value)) || (value['failedMessageCount'] === undefined && value['failed_message_count'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function MigrationMailboxFromJSON(json: any): MigrationMailbox {
    return MigrationMailboxFromJSONTyped(json, false);
}

export function MigrationMailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationMailbox {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'migrationId': json['migration_id'],
        'tenantId': json['tenant_id'],
        'sourceEmail': json['source_email'],
        'destEmail': json['dest_email'] == null ? undefined : json['dest_email'],
        'destMailboxId': json['dest_mailbox_id'] == null ? undefined : json['dest_mailbox_id'],
        'status': json['status'],
        'sourceMessageCount': json['source_message_count'] == null ? undefined : json['source_message_count'],
        'syncedMessageCount': json['synced_message_count'],
        'failedMessageCount': json['failed_message_count'],
        'sourceSizeBytes': json['source_size_bytes'] == null ? undefined : json['source_size_bytes'],
        'syncedSizeBytes': json['synced_size_bytes'] == null ? undefined : json['synced_size_bytes'],
        'lastSyncedUid': json['last_synced_uid'] == null ? undefined : json['last_synced_uid'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : (new Date(json['last_synced_at'])),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function MigrationMailboxToJSON(json: any): MigrationMailbox {
    return MigrationMailboxToJSONTyped(json, false);
}

export function MigrationMailboxToJSONTyped(value?: MigrationMailbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'migration_id': value['migrationId'],
        'tenant_id': value['tenantId'],
        'source_email': value['sourceEmail'],
        'dest_email': value['destEmail'],
        'dest_mailbox_id': value['destMailboxId'],
        'status': value['status'],
        'source_message_count': value['sourceMessageCount'],
        'synced_message_count': value['syncedMessageCount'],
        'failed_message_count': value['failedMessageCount'],
        'source_size_bytes': value['sourceSizeBytes'],
        'synced_size_bytes': value['syncedSizeBytes'],
        'last_synced_uid': value['lastSyncedUid'],
        'last_synced_at': value['lastSyncedAt'] == null ? value['lastSyncedAt'] : value['lastSyncedAt'].toISOString(),
        'error_message': value['errorMessage'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

