/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrationSettings } from './MigrationSettings';
import {
    MigrationSettingsFromJSON,
    MigrationSettingsFromJSONTyped,
    MigrationSettingsToJSON,
    MigrationSettingsToJSONTyped,
} from './MigrationSettings';

/**
 * 
 * @export
 * @interface Migration
 */
export interface Migration {
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    credentialId: string;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    name: string;
    /**
     * 
     * @type {MigrationStatusEnum}
     * @memberof Migration
     */
    status: MigrationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    sourceProvider: string;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    sourceSummary?: string;
    /**
     * 
     * @type {MigrationSettings}
     * @memberof Migration
     */
    settings?: MigrationSettings;
    /**
     * 
     * @type {string}
     * @memberof Migration
     */
    errorMessage?: string;
    /**
     * 
     * @type {Date}
     * @memberof Migration
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Migration
     */
    completedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Migration
     */
    mailboxCount: number;
    /**
     * 
     * @type {Date}
     * @memberof Migration
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Migration
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const MigrationStatusEnum = {
    Draft: 'draft',
    Discovering: 'discovering',
    Discovered: 'discovered',
    Mapped: 'mapped',
    PilotRunning: 'pilot_running',
    PilotComplete: 'pilot_complete',
    Running: 'running',
    Staged: 'staged',
    CutoverPending: 'cutover_pending',
    FinalSyncing: 'final_syncing',
    Validating: 'validating',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type MigrationStatusEnum = typeof MigrationStatusEnum[keyof typeof MigrationStatusEnum];


/**
 * Check if a given object implements the Migration interface.
 */
export function instanceOfMigration(value: object): value is Migration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('credentialId' in value) && !('credential_id' in value)) || (value['credentialId'] === undefined && value['credential_id'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('sourceProvider' in value) && !('source_provider' in value)) || (value['sourceProvider'] === undefined && value['source_provider'] === undefined)) return false;
    if ((!('mailboxCount' in value) && !('mailbox_count' in value)) || (value['mailboxCount'] === undefined && value['mailbox_count'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function MigrationFromJSON(json: any): Migration {
    return MigrationFromJSONTyped(json, false);
}

export function MigrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Migration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'credentialId': json['credential_id'],
        'name': json['name'],
        'status': json['status'],
        'sourceProvider': json['source_provider'],
        'sourceSummary': json['source_summary'] == null ? undefined : json['source_summary'],
        'settings': json['settings'] == null ? undefined : MigrationSettingsFromJSON(json['settings']),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'mailboxCount': json['mailbox_count'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function MigrationToJSON(json: any): Migration {
    return MigrationToJSONTyped(json, false);
}

export function MigrationToJSONTyped(value?: Migration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'credential_id': value['credentialId'],
        'name': value['name'],
        'status': value['status'],
        'source_provider': value['sourceProvider'],
        'source_summary': value['sourceSummary'],
        'settings': MigrationSettingsToJSON(value['settings']),
        'error_message': value['errorMessage'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'mailbox_count': value['mailboxCount'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

