/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MigrationCredential
 */
export interface MigrationCredential {
    /**
     * 
     * @type {string}
     * @memberof MigrationCredential
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationCredential
     */
    tenantId: string;
    /**
     * 
     * @type {MigrationCredentialProviderEnum}
     * @memberof MigrationCredential
     */
    provider: MigrationCredentialProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof MigrationCredential
     */
    encryptionKeyId?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationCredential
     */
    label?: string;
    /**
     * 
     * @type {Date}
     * @memberof MigrationCredential
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MigrationCredential
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const MigrationCredentialProviderEnum = {
    Imap: 'imap',
    Google: 'google',
    Microsoft: 'microsoft',
    Generic: 'generic'
} as const;
export type MigrationCredentialProviderEnum = typeof MigrationCredentialProviderEnum[keyof typeof MigrationCredentialProviderEnum];


/**
 * Check if a given object implements the MigrationCredential interface.
 */
export function instanceOfMigrationCredential(value: object): value is MigrationCredential {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function MigrationCredentialFromJSON(json: any): MigrationCredential {
    return MigrationCredentialFromJSONTyped(json, false);
}

export function MigrationCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'provider': json['provider'],
        'encryptionKeyId': json['encryption_key_id'] == null ? undefined : json['encryption_key_id'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function MigrationCredentialToJSON(json: any): MigrationCredential {
    return MigrationCredentialToJSONTyped(json, false);
}

export function MigrationCredentialToJSONTyped(value?: MigrationCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'provider': value['provider'],
        'encryption_key_id': value['encryptionKeyId'],
        'label': value['label'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

