/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharedMember
 */
export interface SharedMember {
    /**
     * 
     * @type {string}
     * @memberof SharedMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SharedMember
     */
    mailboxId: string;
    /**
     * 
     * @type {string}
     * @memberof SharedMember
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof SharedMember
     */
    memberEmail: string;
    /**
     * 
     * @type {SharedMemberRoleEnum}
     * @memberof SharedMember
     */
    role: SharedMemberRoleEnum;
    /**
     * 
     * @type {Date}
     * @memberof SharedMember
     */
    createdAt: Date;
}


/**
 * @export
 */
export const SharedMemberRoleEnum = {
    Manager: 'manager',
    Member: 'member'
} as const;
export type SharedMemberRoleEnum = typeof SharedMemberRoleEnum[keyof typeof SharedMemberRoleEnum];


/**
 * Check if a given object implements the SharedMember interface.
 */
export function instanceOfSharedMember(value: object): value is SharedMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('mailboxId' in value) && !('mailbox_id' in value)) || (value['mailboxId'] === undefined && value['mailbox_id'] === undefined)) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if ((!('memberEmail' in value) && !('member_email' in value)) || (value['memberEmail'] === undefined && value['member_email'] === undefined)) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function SharedMemberFromJSON(json: any): SharedMember {
    return SharedMemberFromJSONTyped(json, false);
}

export function SharedMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mailboxId': json['mailbox_id'],
        'tenantId': json['tenant_id'],
        'memberEmail': json['member_email'],
        'role': json['role'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function SharedMemberToJSON(json: any): SharedMember {
    return SharedMemberToJSONTyped(json, false);
}

export function SharedMemberToJSONTyped(value?: SharedMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mailbox_id': value['mailboxId'],
        'tenant_id': value['tenantId'],
        'member_email': value['memberEmail'],
        'role': value['role'],
        'created_at': value['createdAt'].toISOString(),
    };
}

