/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    adminEmail: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    password: string;
    /**
     * 
     * @type {SignupRequestModeEnum}
     * @memberof SignupRequest
     */
    mode?: SignupRequestModeEnum;
}


/**
 * @export
 */
export const SignupRequestModeEnum = {
    Api: 'api',
    Business: 'business',
    Both: 'both'
} as const;
export type SignupRequestModeEnum = typeof SignupRequestModeEnum[keyof typeof SignupRequestModeEnum];


/**
 * Check if a given object implements the SignupRequest interface.
 */
export function instanceOfSignupRequest(value: object): value is SignupRequest {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if ((!('adminEmail' in value) && !('admin_email' in value)) || (value['adminEmail'] === undefined && value['admin_email'] === undefined)) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
    return SignupRequestFromJSONTyped(json, false);
}

export function SignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'adminEmail': json['admin_email'],
        'password': json['password'],
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function SignupRequestToJSON(json: any): SignupRequest {
    return SignupRequestToJSONTyped(json, false);
}

export function SignupRequestToJSONTyped(value?: SignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'display_name': value['displayName'],
        'admin_email': value['adminEmail'],
        'password': value['password'],
        'mode': value['mode'],
    };
}

