/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCalendarPoliciesRequest
 */
export interface UpdateCalendarPoliciesRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateCalendarPoliciesRequest
     */
    maxMeetingDurationMins?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarPoliciesRequest
     */
    workingHoursStart?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarPoliciesRequest
     */
    workingHoursEnd?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateCalendarPoliciesRequest
     */
    bookingWindowDays?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCalendarPoliciesRequest
     */
    recurringMeetingLimit?: number;
    /**
     * 
     * @type {UpdateCalendarPoliciesRequestResourceApprovalModeEnum}
     * @memberof UpdateCalendarPoliciesRequest
     */
    resourceApprovalMode?: UpdateCalendarPoliciesRequestResourceApprovalModeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCalendarPoliciesRequest
     */
    externalInvitesAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCalendarPoliciesRequest
     */
    externalSharingAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCalendarPoliciesRequest
     */
    publicLinksEnabled?: boolean;
}


/**
 * @export
 */
export const UpdateCalendarPoliciesRequestResourceApprovalModeEnum = {
    AutoApprove: 'auto_approve',
    RequireApproval: 'require_approval',
    Restricted: 'restricted'
} as const;
export type UpdateCalendarPoliciesRequestResourceApprovalModeEnum = typeof UpdateCalendarPoliciesRequestResourceApprovalModeEnum[keyof typeof UpdateCalendarPoliciesRequestResourceApprovalModeEnum];


/**
 * Check if a given object implements the UpdateCalendarPoliciesRequest interface.
 */
export function instanceOfUpdateCalendarPoliciesRequest(value: object): value is UpdateCalendarPoliciesRequest {
    return true;
}

export function UpdateCalendarPoliciesRequestFromJSON(json: any): UpdateCalendarPoliciesRequest {
    return UpdateCalendarPoliciesRequestFromJSONTyped(json, false);
}

export function UpdateCalendarPoliciesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCalendarPoliciesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxMeetingDurationMins': json['max_meeting_duration_mins'] == null ? undefined : json['max_meeting_duration_mins'],
        'workingHoursStart': json['working_hours_start'] == null ? undefined : json['working_hours_start'],
        'workingHoursEnd': json['working_hours_end'] == null ? undefined : json['working_hours_end'],
        'bookingWindowDays': json['booking_window_days'] == null ? undefined : json['booking_window_days'],
        'recurringMeetingLimit': json['recurring_meeting_limit'] == null ? undefined : json['recurring_meeting_limit'],
        'resourceApprovalMode': json['resource_approval_mode'] == null ? undefined : json['resource_approval_mode'],
        'externalInvitesAllowed': json['external_invites_allowed'] == null ? undefined : json['external_invites_allowed'],
        'externalSharingAllowed': json['external_sharing_allowed'] == null ? undefined : json['external_sharing_allowed'],
        'publicLinksEnabled': json['public_links_enabled'] == null ? undefined : json['public_links_enabled'],
    };
}

export function UpdateCalendarPoliciesRequestToJSON(json: any): UpdateCalendarPoliciesRequest {
    return UpdateCalendarPoliciesRequestToJSONTyped(json, false);
}

export function UpdateCalendarPoliciesRequestToJSONTyped(value?: UpdateCalendarPoliciesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_meeting_duration_mins': value['maxMeetingDurationMins'],
        'working_hours_start': value['workingHoursStart'],
        'working_hours_end': value['workingHoursEnd'],
        'booking_window_days': value['bookingWindowDays'],
        'recurring_meeting_limit': value['recurringMeetingLimit'],
        'resource_approval_mode': value['resourceApprovalMode'],
        'external_invites_allowed': value['externalInvitesAllowed'],
        'external_sharing_allowed': value['externalSharingAllowed'],
        'public_links_enabled': value['publicLinksEnabled'],
    };
}

