/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrationSettings } from './MigrationSettings';
import {
    MigrationSettingsFromJSON,
    MigrationSettingsFromJSONTyped,
    MigrationSettingsToJSON,
    MigrationSettingsToJSONTyped,
} from './MigrationSettings';

/**
 * 
 * @export
 * @interface UpdateMigrationRequest
 */
export interface UpdateMigrationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateMigrationRequest
     */
    name?: string;
    /**
     * 
     * @type {MigrationSettings}
     * @memberof UpdateMigrationRequest
     */
    settings?: MigrationSettings;
}

/**
 * Check if a given object implements the UpdateMigrationRequest interface.
 */
export function instanceOfUpdateMigrationRequest(value: object): value is UpdateMigrationRequest {
    return true;
}

export function UpdateMigrationRequestFromJSON(json: any): UpdateMigrationRequest {
    return UpdateMigrationRequestFromJSONTyped(json, false);
}

export function UpdateMigrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMigrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'settings': json['settings'] == null ? undefined : MigrationSettingsFromJSON(json['settings']),
    };
}

export function UpdateMigrationRequestToJSON(json: any): UpdateMigrationRequest {
    return UpdateMigrationRequestToJSONTyped(json, false);
}

export function UpdateMigrationRequestToJSONTyped(value?: UpdateMigrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'settings': MigrationSettingsToJSON(value['settings']),
    };
}

