/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateContactRequest
 */
export interface UpdateContactRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    notes?: string;
    /**
     * 
     * @type {UpdateContactRequestContactTypeEnum}
     * @memberof UpdateContactRequest
     */
    contactType?: UpdateContactRequestContactTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateContactRequest
     */
    role?: string;
    /**
     * 
     * @type {UpdateContactRequestStatusEnum}
     * @memberof UpdateContactRequest
     */
    status?: UpdateContactRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateContactRequestContactTypeEnum = {
    Internal: 'internal',
    External: 'external'
} as const;
export type UpdateContactRequestContactTypeEnum = typeof UpdateContactRequestContactTypeEnum[keyof typeof UpdateContactRequestContactTypeEnum];

/**
 * @export
 */
export const UpdateContactRequestStatusEnum = {
    Active: 'active',
    Disabled: 'disabled'
} as const;
export type UpdateContactRequestStatusEnum = typeof UpdateContactRequestStatusEnum[keyof typeof UpdateContactRequestStatusEnum];


/**
 * Check if a given object implements the UpdateContactRequest interface.
 */
export function instanceOfUpdateContactRequest(value: object): value is UpdateContactRequest {
    return true;
}

export function UpdateContactRequestFromJSON(json: any): UpdateContactRequest {
    return UpdateContactRequestFromJSONTyped(json, false);
}

export function UpdateContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateContactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'company': json['company'] == null ? undefined : json['company'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'contactType': json['contact_type'] == null ? undefined : json['contact_type'],
        'department': json['department'] == null ? undefined : json['department'],
        'role': json['role'] == null ? undefined : json['role'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateContactRequestToJSON(json: any): UpdateContactRequest {
    return UpdateContactRequestToJSONTyped(json, false);
}

export function UpdateContactRequestToJSONTyped(value?: UpdateContactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'company': value['company'],
        'notes': value['notes'],
        'contact_type': value['contactType'],
        'department': value['department'],
        'role': value['role'],
        'status': value['status'],
    };
}

