/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGALSettingsRequest
 */
export interface UpdateGALSettingsRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGALSettingsRequest
     */
    galEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGALSettingsRequest
     */
    hideFromDirectory?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGALSettingsRequest
     */
    departmentGrouping?: boolean;
    /**
     * 
     * @type {UpdateGALSettingsRequestSearchVisibilityEnum}
     * @memberof UpdateGALSettingsRequest
     */
    searchVisibility?: UpdateGALSettingsRequestSearchVisibilityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGALSettingsRequest
     */
    includeExternalContacts?: boolean;
}


/**
 * @export
 */
export const UpdateGALSettingsRequestSearchVisibilityEnum = {
    AllUsers: 'all_users',
    SameDepartment: 'same_department',
    AdminsOnly: 'admins_only'
} as const;
export type UpdateGALSettingsRequestSearchVisibilityEnum = typeof UpdateGALSettingsRequestSearchVisibilityEnum[keyof typeof UpdateGALSettingsRequestSearchVisibilityEnum];


/**
 * Check if a given object implements the UpdateGALSettingsRequest interface.
 */
export function instanceOfUpdateGALSettingsRequest(value: object): value is UpdateGALSettingsRequest {
    return true;
}

export function UpdateGALSettingsRequestFromJSON(json: any): UpdateGALSettingsRequest {
    return UpdateGALSettingsRequestFromJSONTyped(json, false);
}

export function UpdateGALSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGALSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'galEnabled': json['gal_enabled'] == null ? undefined : json['gal_enabled'],
        'hideFromDirectory': json['hide_from_directory'] == null ? undefined : json['hide_from_directory'],
        'departmentGrouping': json['department_grouping'] == null ? undefined : json['department_grouping'],
        'searchVisibility': json['search_visibility'] == null ? undefined : json['search_visibility'],
        'includeExternalContacts': json['include_external_contacts'] == null ? undefined : json['include_external_contacts'],
    };
}

export function UpdateGALSettingsRequestToJSON(json: any): UpdateGALSettingsRequest {
    return UpdateGALSettingsRequestToJSONTyped(json, false);
}

export function UpdateGALSettingsRequestToJSONTyped(value?: UpdateGALSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gal_enabled': value['galEnabled'],
        'hide_from_directory': value['hideFromDirectory'],
        'department_grouping': value['departmentGrouping'],
        'search_visibility': value['searchVisibility'],
        'include_external_contacts': value['includeExternalContacts'],
    };
}

