/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateResourceRequest
 */
export interface UpdateResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    name?: string;
    /**
     * 
     * @type {UpdateResourceRequestTypeEnum}
     * @memberof UpdateResourceRequest
     */
    type?: UpdateResourceRequestTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateResourceRequest
     */
    capacity?: number;
    /**
     * 
     * @type {UpdateResourceRequestStatusEnum}
     * @memberof UpdateResourceRequest
     */
    status?: UpdateResourceRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateResourceRequestTypeEnum = {
    MeetingRoom: 'meeting_room',
    Equipment: 'equipment'
} as const;
export type UpdateResourceRequestTypeEnum = typeof UpdateResourceRequestTypeEnum[keyof typeof UpdateResourceRequestTypeEnum];

/**
 * @export
 */
export const UpdateResourceRequestStatusEnum = {
    Available: 'available',
    Active: 'active',
    Disabled: 'disabled'
} as const;
export type UpdateResourceRequestStatusEnum = typeof UpdateResourceRequestStatusEnum[keyof typeof UpdateResourceRequestStatusEnum];


/**
 * Check if a given object implements the UpdateResourceRequest interface.
 */
export function instanceOfUpdateResourceRequest(value: object): value is UpdateResourceRequest {
    return true;
}

export function UpdateResourceRequestFromJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestFromJSONTyped(json, false);
}

export function UpdateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateResourceRequestToJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestToJSONTyped(json, false);
}

export function UpdateResourceRequestToJSONTyped(value?: UpdateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'capacity': value['capacity'],
        'status': value['status'],
    };
}

