/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCalendarRequest
 */
export interface UpdateCalendarRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCalendarRequest
     */
    description?: string;
    /**
     * 
     * @type {UpdateCalendarRequestVisibilityEnum}
     * @memberof UpdateCalendarRequest
     */
    visibility?: UpdateCalendarRequestVisibilityEnum;
}


/**
 * @export
 */
export const UpdateCalendarRequestVisibilityEnum = {
    Private: 'private',
    Tenant: 'tenant'
} as const;
export type UpdateCalendarRequestVisibilityEnum = typeof UpdateCalendarRequestVisibilityEnum[keyof typeof UpdateCalendarRequestVisibilityEnum];


/**
 * Check if a given object implements the UpdateCalendarRequest interface.
 */
export function instanceOfUpdateCalendarRequest(value: object): value is UpdateCalendarRequest {
    return true;
}

export function UpdateCalendarRequestFromJSON(json: any): UpdateCalendarRequest {
    return UpdateCalendarRequestFromJSONTyped(json, false);
}

export function UpdateCalendarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCalendarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'description': json['description'] == null ? undefined : json['description'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
    };
}

export function UpdateCalendarRequestToJSON(json: any): UpdateCalendarRequest {
    return UpdateCalendarRequestToJSONTyped(json, false);
}

export function UpdateCalendarRequestToJSONTyped(value?: UpdateCalendarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'owner_email': value['ownerEmail'],
        'description': value['description'],
        'visibility': value['visibility'],
    };
}

