/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserEvent
 */
export interface UserEvent {
    /**
     * 
     * @type {string}
     * @memberof UserEvent
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserEvent
     */
    eventAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UserEvent
     */
    daysInactive?: number;
}

/**
 * Check if a given object implements the UserEvent interface.
 */
export function instanceOfUserEvent(value: object): value is UserEvent {
    return true;
}

export function UserEventFromJSON(json: any): UserEvent {
    return UserEventFromJSONTyped(json, false);
}

export function UserEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'eventAt': json['event_at'] == null ? undefined : (new Date(json['event_at'])),
        'daysInactive': json['days_inactive'] == null ? undefined : json['days_inactive'],
    };
}

export function UserEventToJSON(json: any): UserEvent {
    return UserEventToJSONTyped(json, false);
}

export function UserEventToJSONTyped(value?: UserEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'event_at': value['eventAt'] == null ? value['eventAt'] : value['eventAt'].toISOString(),
        'days_inactive': value['daysInactive'],
    };
}

