/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tenant } from './Tenant';
import {
    TenantFromJSON,
    TenantFromJSONTyped,
    TenantToJSON,
    TenantToJSONTyped,
} from './Tenant';
import type { Admin } from './Admin';
import {
    AdminFromJSON,
    AdminFromJSONTyped,
    AdminToJSON,
    AdminToJSONTyped,
} from './Admin';

/**
 * 
 * @export
 * @interface V1AdminMeGet200Response
 */
export interface V1AdminMeGet200Response {
    /**
     * 
     * @type {Admin}
     * @memberof V1AdminMeGet200Response
     */
    admin: Admin;
    /**
     * 
     * @type {Tenant}
     * @memberof V1AdminMeGet200Response
     */
    tenant: Tenant;
}

/**
 * Check if a given object implements the V1AdminMeGet200Response interface.
 */
export function instanceOfV1AdminMeGet200Response(value: object): value is V1AdminMeGet200Response {
    if (!('admin' in value) || value['admin'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function V1AdminMeGet200ResponseFromJSON(json: any): V1AdminMeGet200Response {
    return V1AdminMeGet200ResponseFromJSONTyped(json, false);
}

export function V1AdminMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AdminMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'admin': AdminFromJSON(json['admin']),
        'tenant': TenantFromJSON(json['tenant']),
    };
}

export function V1AdminMeGet200ResponseToJSON(json: any): V1AdminMeGet200Response {
    return V1AdminMeGet200ResponseToJSONTyped(json, false);
}

export function V1AdminMeGet200ResponseToJSONTyped(value?: V1AdminMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admin': AdminToJSON(value['admin']),
        'tenant': TenantToJSON(value['tenant']),
    };
}

