/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AdminsPostRequest
 */
export interface V1AdminsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1AdminsPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof V1AdminsPostRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AdminsPostRequest
     */
    displayName?: string;
    /**
     * 
     * @type {V1AdminsPostRequestRoleEnum}
     * @memberof V1AdminsPostRequest
     */
    role?: V1AdminsPostRequestRoleEnum;
}


/**
 * @export
 */
export const V1AdminsPostRequestRoleEnum = {
    Admin: 'admin',
    Viewer: 'viewer'
} as const;
export type V1AdminsPostRequestRoleEnum = typeof V1AdminsPostRequestRoleEnum[keyof typeof V1AdminsPostRequestRoleEnum];


/**
 * Check if a given object implements the V1AdminsPostRequest interface.
 */
export function instanceOfV1AdminsPostRequest(value: object): value is V1AdminsPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function V1AdminsPostRequestFromJSON(json: any): V1AdminsPostRequest {
    return V1AdminsPostRequestFromJSONTyped(json, false);
}

export function V1AdminsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AdminsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function V1AdminsPostRequestToJSON(json: any): V1AdminsPostRequest {
    return V1AdminsPostRequestToJSONTyped(json, false);
}

export function V1AdminsPostRequestToJSONTyped(value?: V1AdminsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'display_name': value['displayName'],
        'role': value['role'],
    };
}

