/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AdminsIdPatchRequest
 */
export interface V1AdminsIdPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof V1AdminsIdPatchRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AdminsIdPatchRequest
     */
    displayName?: string;
    /**
     * 
     * @type {V1AdminsIdPatchRequestRoleEnum}
     * @memberof V1AdminsIdPatchRequest
     */
    role?: V1AdminsIdPatchRequestRoleEnum;
    /**
     * 
     * @type {boolean}
     * @memberof V1AdminsIdPatchRequest
     */
    disabled?: boolean;
}


/**
 * @export
 */
export const V1AdminsIdPatchRequestRoleEnum = {
    Admin: 'admin',
    Viewer: 'viewer'
} as const;
export type V1AdminsIdPatchRequestRoleEnum = typeof V1AdminsIdPatchRequestRoleEnum[keyof typeof V1AdminsIdPatchRequestRoleEnum];


/**
 * Check if a given object implements the V1AdminsIdPatchRequest interface.
 */
export function instanceOfV1AdminsIdPatchRequest(value: object): value is V1AdminsIdPatchRequest {
    return true;
}

export function V1AdminsIdPatchRequestFromJSON(json: any): V1AdminsIdPatchRequest {
    return V1AdminsIdPatchRequestFromJSONTyped(json, false);
}

export function V1AdminsIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AdminsIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'role': json['role'] == null ? undefined : json['role'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
    };
}

export function V1AdminsIdPatchRequestToJSON(json: any): V1AdminsIdPatchRequest {
    return V1AdminsIdPatchRequestToJSONTyped(json, false);
}

export function V1AdminsIdPatchRequestToJSONTyped(value?: V1AdminsIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'display_name': value['displayName'],
        'role': value['role'],
        'disabled': value['disabled'],
    };
}

