/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AliasesPostRequest
 */
export interface V1AliasesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1AliasesPostRequest
     */
    aliasAddress: string;
    /**
     * 
     * @type {string}
     * @memberof V1AliasesPostRequest
     */
    aliasTarget: string;
}

/**
 * Check if a given object implements the V1AliasesPostRequest interface.
 */
export function instanceOfV1AliasesPostRequest(value: object): value is V1AliasesPostRequest {
    if ((!('aliasAddress' in value) && !('alias_address' in value)) || (value['aliasAddress'] === undefined && value['alias_address'] === undefined)) return false;
    if ((!('aliasTarget' in value) && !('alias_target' in value)) || (value['aliasTarget'] === undefined && value['alias_target'] === undefined)) return false;
    return true;
}

export function V1AliasesPostRequestFromJSON(json: any): V1AliasesPostRequest {
    return V1AliasesPostRequestFromJSONTyped(json, false);
}

export function V1AliasesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AliasesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'aliasAddress': json['alias_address'],
        'aliasTarget': json['alias_target'],
    };
}

export function V1AliasesPostRequestToJSON(json: any): V1AliasesPostRequest {
    return V1AliasesPostRequestToJSONTyped(json, false);
}

export function V1AliasesPostRequestToJSONTyped(value?: V1AliasesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias_address': value['aliasAddress'],
        'alias_target': value['aliasTarget'],
    };
}

