/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ApiKeysPost201Response
 */
export interface V1ApiKeysPost201Response {
    /**
     * 
     * @type {string}
     * @memberof V1ApiKeysPost201Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1ApiKeysPost201Response
     */
    tenantId: string;
    /**
     * 8-char public prefix; safe to store and display.
     * @type {string}
     * @memberof V1ApiKeysPost201Response
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ApiKeysPost201Response
     */
    scopes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ApiKeysPost201Response
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKeysPost201Response
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKeysPost201Response
     */
    revokedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKeysPost201Response
     */
    createdAt: Date;
    /**
     * The full `lk_live_<prefix>_<secret>` token. Shown ONCE.
     * @type {string}
     * @memberof V1ApiKeysPost201Response
     */
    secret: string;
}

/**
 * Check if a given object implements the V1ApiKeysPost201Response interface.
 */
export function instanceOfV1ApiKeysPost201Response(value: object): value is V1ApiKeysPost201Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('tenantId' in value) && !('tenant_id' in value)) || (value['tenantId'] === undefined && value['tenant_id'] === undefined)) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function V1ApiKeysPost201ResponseFromJSON(json: any): V1ApiKeysPost201Response {
    return V1ApiKeysPost201ResponseFromJSONTyped(json, false);
}

export function V1ApiKeysPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ApiKeysPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenant_id'],
        'prefix': json['prefix'],
        'scopes': json['scopes'],
        'label': json['label'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'revokedAt': json['revoked_at'] == null ? undefined : (new Date(json['revoked_at'])),
        'createdAt': (new Date(json['created_at'])),
        'secret': json['secret'],
    };
}

export function V1ApiKeysPost201ResponseToJSON(json: any): V1ApiKeysPost201Response {
    return V1ApiKeysPost201ResponseToJSONTyped(json, false);
}

export function V1ApiKeysPost201ResponseToJSONTyped(value?: V1ApiKeysPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant_id': value['tenantId'],
        'prefix': value['prefix'],
        'scopes': value['scopes'],
        'label': value['label'],
        'last_used_at': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'revoked_at': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'secret': value['secret'],
    };
}

