/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1DomainsPostRequest
 */
export interface V1DomainsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1DomainsPostRequest
     */
    domain: string;
}

/**
 * Check if a given object implements the V1DomainsPostRequest interface.
 */
export function instanceOfV1DomainsPostRequest(value: object): value is V1DomainsPostRequest {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function V1DomainsPostRequestFromJSON(json: any): V1DomainsPostRequest {
    return V1DomainsPostRequestFromJSONTyped(json, false);
}

export function V1DomainsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DomainsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
    };
}

export function V1DomainsPostRequestToJSON(json: any): V1DomainsPostRequest {
    return V1DomainsPostRequestToJSONTyped(json, false);
}

export function V1DomainsPostRequestToJSONTyped(value?: V1DomainsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
    };
}

