/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1MailboxesEmailPatchRequest
 */
export interface V1MailboxesEmailPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof V1MailboxesEmailPatchRequest
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof V1MailboxesEmailPatchRequest
     */
    quotaBytes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1MailboxesEmailPatchRequest
     */
    disabled?: boolean;
}

/**
 * Check if a given object implements the V1MailboxesEmailPatchRequest interface.
 */
export function instanceOfV1MailboxesEmailPatchRequest(value: object): value is V1MailboxesEmailPatchRequest {
    return true;
}

export function V1MailboxesEmailPatchRequestFromJSON(json: any): V1MailboxesEmailPatchRequest {
    return V1MailboxesEmailPatchRequestFromJSONTyped(json, false);
}

export function V1MailboxesEmailPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MailboxesEmailPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'quotaBytes': json['quota_bytes'] == null ? undefined : json['quota_bytes'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
    };
}

export function V1MailboxesEmailPatchRequestToJSON(json: any): V1MailboxesEmailPatchRequest {
    return V1MailboxesEmailPatchRequestToJSONTyped(json, false);
}

export function V1MailboxesEmailPatchRequestToJSONTyped(value?: V1MailboxesEmailPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'quota_bytes': value['quotaBytes'],
        'disabled': value['disabled'],
    };
}

