/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1MailboxesEmailExportPost201Response
 */
export interface V1MailboxesEmailExportPost201Response {
    /**
     * Relative download URL. Caller appends to the API host.
     * @type {string}
     * @memberof V1MailboxesEmailExportPost201Response
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof V1MailboxesEmailExportPost201Response
     */
    expiresAt: Date;
    /**
     * 
     * @type {V1MailboxesEmailExportPost201ResponseFormatEnum}
     * @memberof V1MailboxesEmailExportPost201Response
     */
    format: V1MailboxesEmailExportPost201ResponseFormatEnum;
}


/**
 * @export
 */
export const V1MailboxesEmailExportPost201ResponseFormatEnum = {
    Mbox: 'mbox'
} as const;
export type V1MailboxesEmailExportPost201ResponseFormatEnum = typeof V1MailboxesEmailExportPost201ResponseFormatEnum[keyof typeof V1MailboxesEmailExportPost201ResponseFormatEnum];


/**
 * Check if a given object implements the V1MailboxesEmailExportPost201Response interface.
 */
export function instanceOfV1MailboxesEmailExportPost201Response(value: object): value is V1MailboxesEmailExportPost201Response {
    if (!('url' in value) || value['url'] === undefined) return false;
    if ((!('expiresAt' in value) && !('expires_at' in value)) || (value['expiresAt'] === undefined && value['expires_at'] === undefined)) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (value['format'] !== 'mbox') return false;
    
    return true;
}

export function V1MailboxesEmailExportPost201ResponseFromJSON(json: any): V1MailboxesEmailExportPost201Response {
    return V1MailboxesEmailExportPost201ResponseFromJSONTyped(json, false);
}

export function V1MailboxesEmailExportPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MailboxesEmailExportPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'expiresAt': (new Date(json['expires_at'])),
        'format': json['format'],
    };
}

export function V1MailboxesEmailExportPost201ResponseToJSON(json: any): V1MailboxesEmailExportPost201Response {
    return V1MailboxesEmailExportPost201ResponseToJSONTyped(json, false);
}

export function V1MailboxesEmailExportPost201ResponseToJSONTyped(value?: V1MailboxesEmailExportPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'expires_at': value['expiresAt'].toISOString(),
        'format': value['format'],
    };
}

