/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1MailboxesPostRequest
 */
export interface V1MailboxesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1MailboxesPostRequest
     */
    email: string;
    /**
     * Optional; lockally generates if absent.
     * @type {string}
     * @memberof V1MailboxesPostRequest
     */
    password?: string;
    /**
     * 5 GB default.
     * @type {number}
     * @memberof V1MailboxesPostRequest
     */
    quotaBytes?: number;
}

/**
 * Check if a given object implements the V1MailboxesPostRequest interface.
 */
export function instanceOfV1MailboxesPostRequest(value: object): value is V1MailboxesPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function V1MailboxesPostRequestFromJSON(json: any): V1MailboxesPostRequest {
    return V1MailboxesPostRequestFromJSONTyped(json, false);
}

export function V1MailboxesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MailboxesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'quotaBytes': json['quota_bytes'] == null ? undefined : json['quota_bytes'],
    };
}

export function V1MailboxesPostRequestToJSON(json: any): V1MailboxesPostRequest {
    return V1MailboxesPostRequestToJSONTyped(json, false);
}

export function V1MailboxesPostRequestToJSONTyped(value?: V1MailboxesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'quota_bytes': value['quotaBytes'],
    };
}

