/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VacationParams } from './VacationParams';
import {
    VacationParamsFromJSON,
    VacationParamsFromJSONTyped,
    VacationParamsToJSON,
    VacationParamsToJSONTyped,
} from './VacationParams';

/**
 * 
 * @export
 * @interface V1MailboxesEmailVacationPutRequest
 */
export interface V1MailboxesEmailVacationPutRequest {
    /**
     * 
     * @type {boolean}
     * @memberof V1MailboxesEmailVacationPutRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {VacationParams}
     * @memberof V1MailboxesEmailVacationPutRequest
     */
    params: VacationParams;
}

/**
 * Check if a given object implements the V1MailboxesEmailVacationPutRequest interface.
 */
export function instanceOfV1MailboxesEmailVacationPutRequest(value: object): value is V1MailboxesEmailVacationPutRequest {
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function V1MailboxesEmailVacationPutRequestFromJSON(json: any): V1MailboxesEmailVacationPutRequest {
    return V1MailboxesEmailVacationPutRequestFromJSONTyped(json, false);
}

export function V1MailboxesEmailVacationPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MailboxesEmailVacationPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'params': VacationParamsFromJSON(json['params']),
    };
}

export function V1MailboxesEmailVacationPutRequestToJSON(json: any): V1MailboxesEmailVacationPutRequest {
    return V1MailboxesEmailVacationPutRequestToJSONTyped(json, false);
}

export function V1MailboxesEmailVacationPutRequestToJSONTyped(value?: V1MailboxesEmailVacationPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'params': VacationParamsToJSON(value['params']),
    };
}

