/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SendPostRequestAttachmentsInner } from './V1SendPostRequestAttachmentsInner';
import {
    V1SendPostRequestAttachmentsInnerFromJSON,
    V1SendPostRequestAttachmentsInnerFromJSONTyped,
    V1SendPostRequestAttachmentsInnerToJSON,
    V1SendPostRequestAttachmentsInnerToJSONTyped,
} from './V1SendPostRequestAttachmentsInner';

/**
 * 
 * @export
 * @interface V1SendPostRequest
 */
export interface V1SendPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1SendPostRequest
     */
    from: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1SendPostRequest
     */
    to: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1SendPostRequest
     */
    cc?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1SendPostRequest
     */
    bcc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1SendPostRequest
     */
    subject?: string;
    /**
     * Plain-text body. Required if `html` is absent.
     * @type {string}
     * @memberof V1SendPostRequest
     */
    text?: string;
    /**
     * HTML body. Required if `text` is absent.
     * @type {string}
     * @memberof V1SendPostRequest
     */
    html?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof V1SendPostRequest
     */
    headers?: { [key: string]: string; };
    /**
     * Mark as opt-in/broadcast: skips suppressed recipients and adds a managed one-click List-Unsubscribe header.
     * @type {boolean}
     * @memberof V1SendPostRequest
     */
    unsubscribe?: boolean;
    /**
     * Render subject/text/html from a stored template (GET /v1/templates). Mutually exclusive with inline subject/text/html.
     * @type {string}
     * @memberof V1SendPostRequest
     */
    templateId?: string;
    /**
     * Values substituted into the template's {{variable}} placeholders.
     * @type {{ [key: string]: string; }}
     * @memberof V1SendPostRequest
     */
    variables?: { [key: string]: string; };
    /**
     * Schedule delivery for a future RFC3339 time (≤ 30 days out). Omit or past = send now. Cancel with DELETE /v1/messages/{id} while scheduled.
     * @type {Date}
     * @memberof V1SendPostRequest
     */
    sendAt?: Date;
    /**
     * 
     * @type {Array<V1SendPostRequestAttachmentsInner>}
     * @memberof V1SendPostRequest
     */
    attachments?: Array<V1SendPostRequestAttachmentsInner>;
}

/**
 * Check if a given object implements the V1SendPostRequest interface.
 */
export function instanceOfV1SendPostRequest(value: object): value is V1SendPostRequest {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function V1SendPostRequestFromJSON(json: any): V1SendPostRequest {
    return V1SendPostRequestFromJSONTyped(json, false);
}

export function V1SendPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SendPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'cc': json['cc'] == null ? undefined : json['cc'],
        'bcc': json['bcc'] == null ? undefined : json['bcc'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'text': json['text'] == null ? undefined : json['text'],
        'html': json['html'] == null ? undefined : json['html'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'unsubscribe': json['unsubscribe'] == null ? undefined : json['unsubscribe'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'variables': json['variables'] == null ? undefined : json['variables'],
        'sendAt': json['send_at'] == null ? undefined : (new Date(json['send_at'])),
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(V1SendPostRequestAttachmentsInnerFromJSON)),
    };
}

export function V1SendPostRequestToJSON(json: any): V1SendPostRequest {
    return V1SendPostRequestToJSONTyped(json, false);
}

export function V1SendPostRequestToJSONTyped(value?: V1SendPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'cc': value['cc'],
        'bcc': value['bcc'],
        'subject': value['subject'],
        'text': value['text'],
        'html': value['html'],
        'headers': value['headers'],
        'unsubscribe': value['unsubscribe'],
        'template_id': value['templateId'],
        'variables': value['variables'],
        'send_at': value['sendAt'] == null ? value['sendAt'] : value['sendAt'].toISOString(),
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(V1SendPostRequestAttachmentsInnerToJSON)),
    };
}

