/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendMessage } from './SendMessage';
import {
    SendMessageFromJSON,
    SendMessageFromJSONTyped,
    SendMessageToJSON,
    SendMessageToJSONTyped,
} from './SendMessage';

/**
 * 
 * @export
 * @interface V1SendBatchPostRequest
 */
export interface V1SendBatchPostRequest {
    /**
     * 
     * @type {Array<SendMessage>}
     * @memberof V1SendBatchPostRequest
     */
    messages: Array<SendMessage>;
}

/**
 * Check if a given object implements the V1SendBatchPostRequest interface.
 */
export function instanceOfV1SendBatchPostRequest(value: object): value is V1SendBatchPostRequest {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function V1SendBatchPostRequestFromJSON(json: any): V1SendBatchPostRequest {
    return V1SendBatchPostRequestFromJSONTyped(json, false);
}

export function V1SendBatchPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SendBatchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(SendMessageFromJSON)),
    };
}

export function V1SendBatchPostRequestToJSON(json: any): V1SendBatchPostRequest {
    return V1SendBatchPostRequestToJSONTyped(json, false);
}

export function V1SendBatchPostRequestToJSONTyped(value?: V1SendBatchPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(SendMessageToJSON)),
    };
}

