/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SendPostRequestAttachmentsInner
 */
export interface V1SendPostRequestAttachmentsInner {
    /**
     * 
     * @type {string}
     * @memberof V1SendPostRequestAttachmentsInner
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof V1SendPostRequestAttachmentsInner
     */
    contentType: string;
    /**
     * Base64-encoded body, max 10 MB decoded per attachment.
     * @type {string}
     * @memberof V1SendPostRequestAttachmentsInner
     */
    contentBase64: string;
}

/**
 * Check if a given object implements the V1SendPostRequestAttachmentsInner interface.
 */
export function instanceOfV1SendPostRequestAttachmentsInner(value: object): value is V1SendPostRequestAttachmentsInner {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if ((!('contentType' in value) && !('content_type' in value)) || (value['contentType'] === undefined && value['content_type'] === undefined)) return false;
    if ((!('contentBase64' in value) && !('content_base64' in value)) || (value['contentBase64'] === undefined && value['content_base64'] === undefined)) return false;
    return true;
}

export function V1SendPostRequestAttachmentsInnerFromJSON(json: any): V1SendPostRequestAttachmentsInner {
    return V1SendPostRequestAttachmentsInnerFromJSONTyped(json, false);
}

export function V1SendPostRequestAttachmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SendPostRequestAttachmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'contentType': json['content_type'],
        'contentBase64': json['content_base64'],
    };
}

export function V1SendPostRequestAttachmentsInnerToJSON(json: any): V1SendPostRequestAttachmentsInner {
    return V1SendPostRequestAttachmentsInnerToJSONTyped(json, false);
}

export function V1SendPostRequestAttachmentsInnerToJSONTyped(value?: V1SendPostRequestAttachmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'content_type': value['contentType'],
        'content_base64': value['contentBase64'],
    };
}

