/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Suppression } from './Suppression';
import {
    SuppressionFromJSON,
    SuppressionFromJSONTyped,
    SuppressionToJSON,
    SuppressionToJSONTyped,
} from './Suppression';

/**
 * 
 * @export
 * @interface V1SuppressionsGet200Response
 */
export interface V1SuppressionsGet200Response {
    /**
     * 
     * @type {Array<Suppression>}
     * @memberof V1SuppressionsGet200Response
     */
    data?: Array<Suppression>;
    /**
     * 
     * @type {string}
     * @memberof V1SuppressionsGet200Response
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the V1SuppressionsGet200Response interface.
 */
export function instanceOfV1SuppressionsGet200Response(value: object): value is V1SuppressionsGet200Response {
    return true;
}

export function V1SuppressionsGet200ResponseFromJSON(json: any): V1SuppressionsGet200Response {
    return V1SuppressionsGet200ResponseFromJSONTyped(json, false);
}

export function V1SuppressionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SuppressionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SuppressionFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function V1SuppressionsGet200ResponseToJSON(json: any): V1SuppressionsGet200Response {
    return V1SuppressionsGet200ResponseToJSONTyped(json, false);
}

export function V1SuppressionsGet200ResponseToJSONTyped(value?: V1SuppressionsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SuppressionToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

