/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1WebhooksIdPatchRequest
 */
export interface V1WebhooksIdPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof V1WebhooksIdPatchRequest
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1WebhooksIdPatchRequest
     */
    events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof V1WebhooksIdPatchRequest
     */
    paused?: boolean;
}

/**
 * Check if a given object implements the V1WebhooksIdPatchRequest interface.
 */
export function instanceOfV1WebhooksIdPatchRequest(value: object): value is V1WebhooksIdPatchRequest {
    return true;
}

export function V1WebhooksIdPatchRequestFromJSON(json: any): V1WebhooksIdPatchRequest {
    return V1WebhooksIdPatchRequestFromJSONTyped(json, false);
}

export function V1WebhooksIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1WebhooksIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : json['events'],
        'paused': json['paused'] == null ? undefined : json['paused'],
    };
}

export function V1WebhooksIdPatchRequestToJSON(json: any): V1WebhooksIdPatchRequest {
    return V1WebhooksIdPatchRequestToJSONTyped(json, false);
}

export function V1WebhooksIdPatchRequestToJSONTyped(value?: V1WebhooksIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'events': value['events'],
        'paused': value['paused'],
    };
}

