/* tslint:disable */
/* eslint-disable */
/**
 * lockally control plane
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VacationParams } from './VacationParams';
import {
    VacationParamsFromJSON,
    VacationParamsFromJSONTyped,
    VacationParamsToJSON,
    VacationParamsToJSONTyped,
} from './VacationParams';

/**
 * 
 * @export
 * @interface VacationResponder
 */
export interface VacationResponder {
    /**
     * 
     * @type {string}
     * @memberof VacationResponder
     */
    mailboxEmail: string;
    /**
     * 
     * @type {boolean}
     * @memberof VacationResponder
     */
    enabled: boolean;
    /**
     * 
     * @type {VacationParams}
     * @memberof VacationResponder
     */
    params: VacationParams;
    /**
     * Pre-rendered Sieve script (RFC 5230).
     * @type {string}
     * @memberof VacationResponder
     */
    script: string;
    /**
     * Null = stored on lockally but not yet pushed to the mail server.
     * @type {Date}
     * @memberof VacationResponder
     */
    syncedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof VacationResponder
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VacationResponder
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the VacationResponder interface.
 */
export function instanceOfVacationResponder(value: object): value is VacationResponder {
    if ((!('mailboxEmail' in value) && !('mailbox_email' in value)) || (value['mailboxEmail'] === undefined && value['mailbox_email'] === undefined)) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('script' in value) || value['script'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined)) return false;
    return true;
}

export function VacationResponderFromJSON(json: any): VacationResponder {
    return VacationResponderFromJSONTyped(json, false);
}

export function VacationResponderFromJSONTyped(json: any, ignoreDiscriminator: boolean): VacationResponder {
    if (json == null) {
        return json;
    }
    return {
        
        'mailboxEmail': json['mailbox_email'],
        'enabled': json['enabled'],
        'params': VacationParamsFromJSON(json['params']),
        'script': json['script'],
        'syncedAt': json['synced_at'] == null ? undefined : (new Date(json['synced_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function VacationResponderToJSON(json: any): VacationResponder {
    return VacationResponderToJSONTyped(json, false);
}

export function VacationResponderToJSONTyped(value?: VacationResponder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailbox_email': value['mailboxEmail'],
        'enabled': value['enabled'],
        'params': VacationParamsToJSON(value['params']),
        'script': value['script'],
        'synced_at': value['syncedAt'] == null ? value['syncedAt'] : value['syncedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

